// <auto-generated />
using System;
using CarbonFiles.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarbonFiles.Infrastructure.Migrations
{
    [DbContext(typeof(CarbonFilesDbContext))]
    partial class CarbonFilesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("CarbonFiles.Infrastructure.Data.Entities.ApiKeyEntity", b =>
                {
                    b.Property<string>("Prefix")
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("HashedSecret")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Prefix");

                    b.ToTable("ApiKeys", (string)null);
                });

            modelBuilder.Entity("CarbonFiles.Infrastructure.Data.Entities.BucketEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<long>("DownloadCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FileCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerKeyPrefix")
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalSize")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Owner");

                    b.HasIndex("OwnerKeyPrefix");

                    b.ToTable("Buckets", (string)null);
                });

            modelBuilder.Entity("CarbonFiles.Infrastructure.Data.Entities.FileEntity", b =>
                {
                    b.Property<string>("BucketId")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortCode")
                        .HasMaxLength(6)
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("BucketId", "Path");

                    b.HasIndex("BucketId");

                    b.HasIndex("ShortCode")
                        .IsUnique()
                        .HasFilter("ShortCode IS NOT NULL");

                    b.ToTable("Files", (string)null);
                });

            modelBuilder.Entity("CarbonFiles.Infrastructure.Data.Entities.ShortUrlEntity", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(6)
                        .HasColumnType("TEXT");

                    b.Property<string>("BucketId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.HasIndex("BucketId", "FilePath");

                    b.ToTable("ShortUrls", (string)null);
                });

            modelBuilder.Entity("CarbonFiles.Infrastructure.Data.Entities.UploadTokenEntity", b =>
                {
                    b.Property<string>("Token")
                        .HasMaxLength(55)
                        .HasColumnType("TEXT");

                    b.Property<string>("BucketId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxUploads")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UploadsUsed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Token");

                    b.HasIndex("BucketId");

                    b.ToTable("UploadTokens", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
