// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using CarbonFiles.Infrastructure.Data.Entities;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal;

#pragma warning disable 219, 612, 618
#nullable disable

namespace CarbonFiles.Infrastructure.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class ApiKeyEntityEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "CarbonFiles.Infrastructure.Data.Entities.ApiKeyEntity",
                typeof(ApiKeyEntity),
                baseEntityType,
                propertyCount: 5,
                keyCount: 1);

            var prefix = runtimeEntityType.AddProperty(
                "Prefix",
                typeof(string),
                propertyInfo: typeof(ApiKeyEntity).GetProperty("Prefix", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ApiKeyEntity).GetField("<Prefix>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                maxLength: 13);
            prefix.SetGetter(
                string (ApiKeyEntity instance) => ApiKeyEntityUnsafeAccessors.Prefix(instance),
                bool (ApiKeyEntity instance) => ApiKeyEntityUnsafeAccessors.Prefix(instance) == null);
            prefix.SetSetter(
                ApiKeyEntity (ApiKeyEntity instance, string value) =>
                {
                    ApiKeyEntityUnsafeAccessors.Prefix(instance) = value;
                    return instance;
                });
            prefix.SetMaterializationSetter(
                ApiKeyEntity (ApiKeyEntity instance, string value) =>
                {
                    ApiKeyEntityUnsafeAccessors.Prefix(instance) = value;
                    return instance;
                });
            prefix.SetAccessors(
                string (IInternalEntry entry) => ApiKeyEntityUnsafeAccessors.Prefix(((ApiKeyEntity)(entry.Entity))),
                string (IInternalEntry entry) => ApiKeyEntityUnsafeAccessors.Prefix(((ApiKeyEntity)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(prefix, 0),
                string (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<string>(prefix, 0));
            prefix.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: -1);
            prefix.TypeMapping = SqliteStringTypeMapping.Default;
            prefix.SetCurrentValueComparer(new EntryCurrentValueComparer<string>(prefix));

            var createdAt = runtimeEntityType.AddProperty(
                "CreatedAt",
                typeof(DateTime),
                propertyInfo: typeof(ApiKeyEntity).GetProperty("CreatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ApiKeyEntity).GetField("<CreatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            createdAt.SetGetter(
                DateTime (ApiKeyEntity instance) => ApiKeyEntityUnsafeAccessors.CreatedAt(instance),
                bool (ApiKeyEntity instance) => ApiKeyEntityUnsafeAccessors.CreatedAt(instance) == default(DateTime));
            createdAt.SetSetter(
                ApiKeyEntity (ApiKeyEntity instance, DateTime value) =>
                {
                    ApiKeyEntityUnsafeAccessors.CreatedAt(instance) = value;
                    return instance;
                });
            createdAt.SetMaterializationSetter(
                ApiKeyEntity (ApiKeyEntity instance, DateTime value) =>
                {
                    ApiKeyEntityUnsafeAccessors.CreatedAt(instance) = value;
                    return instance;
                });
            createdAt.SetAccessors(
                DateTime (IInternalEntry entry) => ApiKeyEntityUnsafeAccessors.CreatedAt(((ApiKeyEntity)(entry.Entity))),
                DateTime (IInternalEntry entry) => ApiKeyEntityUnsafeAccessors.CreatedAt(((ApiKeyEntity)(entry.Entity))),
                DateTime (IInternalEntry entry) => entry.ReadOriginalValue<DateTime>(createdAt, 1),
                DateTime (IInternalEntry entry) => entry.GetCurrentValue<DateTime>(createdAt));
            createdAt.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            createdAt.TypeMapping = SqliteDateTimeTypeMapping.Default;

            var hashedSecret = runtimeEntityType.AddProperty(
                "HashedSecret",
                typeof(string),
                propertyInfo: typeof(ApiKeyEntity).GetProperty("HashedSecret", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ApiKeyEntity).GetField("<HashedSecret>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 64);
            hashedSecret.SetGetter(
                string (ApiKeyEntity instance) => ApiKeyEntityUnsafeAccessors.HashedSecret(instance),
                bool (ApiKeyEntity instance) => ApiKeyEntityUnsafeAccessors.HashedSecret(instance) == null);
            hashedSecret.SetSetter(
                ApiKeyEntity (ApiKeyEntity instance, string value) =>
                {
                    ApiKeyEntityUnsafeAccessors.HashedSecret(instance) = value;
                    return instance;
                });
            hashedSecret.SetMaterializationSetter(
                ApiKeyEntity (ApiKeyEntity instance, string value) =>
                {
                    ApiKeyEntityUnsafeAccessors.HashedSecret(instance) = value;
                    return instance;
                });
            hashedSecret.SetAccessors(
                string (IInternalEntry entry) => ApiKeyEntityUnsafeAccessors.HashedSecret(((ApiKeyEntity)(entry.Entity))),
                string (IInternalEntry entry) => ApiKeyEntityUnsafeAccessors.HashedSecret(((ApiKeyEntity)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(hashedSecret, 2),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(hashedSecret));
            hashedSecret.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            hashedSecret.TypeMapping = SqliteStringTypeMapping.Default;

            var lastUsedAt = runtimeEntityType.AddProperty(
                "LastUsedAt",
                typeof(DateTime?),
                propertyInfo: typeof(ApiKeyEntity).GetProperty("LastUsedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ApiKeyEntity).GetField("<LastUsedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            lastUsedAt.SetGetter(
                DateTime? (ApiKeyEntity instance) => ApiKeyEntityUnsafeAccessors.LastUsedAt(instance),
                bool (ApiKeyEntity instance) => !(ApiKeyEntityUnsafeAccessors.LastUsedAt(instance).HasValue));
            lastUsedAt.SetSetter(
                ApiKeyEntity (ApiKeyEntity instance, DateTime? value) =>
                {
                    ApiKeyEntityUnsafeAccessors.LastUsedAt(instance) = value;
                    return instance;
                });
            lastUsedAt.SetMaterializationSetter(
                ApiKeyEntity (ApiKeyEntity instance, DateTime? value) =>
                {
                    ApiKeyEntityUnsafeAccessors.LastUsedAt(instance) = value;
                    return instance;
                });
            lastUsedAt.SetAccessors(
                DateTime? (IInternalEntry entry) => ApiKeyEntityUnsafeAccessors.LastUsedAt(((ApiKeyEntity)(entry.Entity))),
                DateTime? (IInternalEntry entry) => ApiKeyEntityUnsafeAccessors.LastUsedAt(((ApiKeyEntity)(entry.Entity))),
                DateTime? (IInternalEntry entry) => entry.ReadOriginalValue<DateTime?>(lastUsedAt, 3),
                DateTime? (IInternalEntry entry) => entry.GetCurrentValue<DateTime?>(lastUsedAt));
            lastUsedAt.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            lastUsedAt.TypeMapping = SqliteDateTimeTypeMapping.Default;
            lastUsedAt.SetComparer(new NullableValueComparer<DateTime>(lastUsedAt.TypeMapping.Comparer));
            lastUsedAt.SetKeyComparer(new NullableValueComparer<DateTime>(lastUsedAt.TypeMapping.KeyComparer));

            var name = runtimeEntityType.AddProperty(
                "Name",
                typeof(string),
                propertyInfo: typeof(ApiKeyEntity).GetProperty("Name", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ApiKeyEntity).GetField("<Name>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 255);
            name.SetGetter(
                string (ApiKeyEntity instance) => ApiKeyEntityUnsafeAccessors.Name(instance),
                bool (ApiKeyEntity instance) => ApiKeyEntityUnsafeAccessors.Name(instance) == null);
            name.SetSetter(
                ApiKeyEntity (ApiKeyEntity instance, string value) =>
                {
                    ApiKeyEntityUnsafeAccessors.Name(instance) = value;
                    return instance;
                });
            name.SetMaterializationSetter(
                ApiKeyEntity (ApiKeyEntity instance, string value) =>
                {
                    ApiKeyEntityUnsafeAccessors.Name(instance) = value;
                    return instance;
                });
            name.SetAccessors(
                string (IInternalEntry entry) => ApiKeyEntityUnsafeAccessors.Name(((ApiKeyEntity)(entry.Entity))),
                string (IInternalEntry entry) => ApiKeyEntityUnsafeAccessors.Name(((ApiKeyEntity)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(name, 4),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(name));
            name.SetPropertyIndexes(
                index: 4,
                originalValueIndex: 4,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            name.TypeMapping = SqliteStringTypeMapping.Default;

            var key = runtimeEntityType.AddKey(
                new[] { prefix });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var prefix = runtimeEntityType.FindProperty("Prefix");
            var createdAt = runtimeEntityType.FindProperty("CreatedAt");
            var hashedSecret = runtimeEntityType.FindProperty("HashedSecret");
            var lastUsedAt = runtimeEntityType.FindProperty("LastUsedAt");
            var name = runtimeEntityType.FindProperty("Name");
            var key = runtimeEntityType.FindKey(new[] { prefix });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNullableFactory<string, int>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<string>(key));
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((ApiKeyEntity)(source.Entity));
                    return ((ISnapshot)(new Snapshot<string, DateTime, string, DateTime?, string>((source.GetCurrentValue<string>(prefix) == null ? null : ((ValueComparer<string>)(((IProperty)prefix).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(prefix))), ((ValueComparer<DateTime>)(((IProperty)createdAt).GetValueComparer())).Snapshot(source.GetCurrentValue<DateTime>(createdAt)), (source.GetCurrentValue<string>(hashedSecret) == null ? null : ((ValueComparer<string>)(((IProperty)hashedSecret).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(hashedSecret))), (source.GetCurrentValue<DateTime?>(lastUsedAt) == null ? null : ((ValueComparer<DateTime?>)(((IProperty)lastUsedAt).GetValueComparer())).Snapshot(source.GetCurrentValue<DateTime?>(lastUsedAt))), (source.GetCurrentValue<string>(name) == null ? null : ((ValueComparer<string>)(((IProperty)name).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(name))))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => Snapshot.Empty);
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((ApiKeyEntity)(source.Entity));
                    return ((ISnapshot)(new Snapshot<string>((source.GetCurrentValue<string>(prefix) == null ? null : ((ValueComparer<string>)(((IProperty)prefix).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<string>(prefix))))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 5,
                navigationCount: 0,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 5,
                shadowCount: 0,
                relationshipCount: 1,
                storeGeneratedCount: 0));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "ApiKeys");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
