// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using CarbonFiles.Infrastructure.Data.Entities;

#pragma warning disable 219, 612, 618
#nullable disable

namespace CarbonFiles.Infrastructure.Data.CompiledModels
{
    public static class ApiKeyEntityUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Prefix>k__BackingField")]
        public static extern ref string Prefix(ApiKeyEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedAt>k__BackingField")]
        public static extern ref DateTime CreatedAt(ApiKeyEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<HashedSecret>k__BackingField")]
        public static extern ref string HashedSecret(ApiKeyEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LastUsedAt>k__BackingField")]
        public static extern ref DateTime? LastUsedAt(ApiKeyEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Name>k__BackingField")]
        public static extern ref string Name(ApiKeyEntity @this);
    }
}
