// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using CarbonFiles.Infrastructure.Data.Entities;

#pragma warning disable 219, 612, 618
#nullable disable

namespace CarbonFiles.Infrastructure.Data.CompiledModels
{
    public static class BucketEntityUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref string Id(BucketEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedAt>k__BackingField")]
        public static extern ref DateTime CreatedAt(BucketEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Description>k__BackingField")]
        public static extern ref string Description(BucketEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<DownloadCount>k__BackingField")]
        public static extern ref long DownloadCount(BucketEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ExpiresAt>k__BackingField")]
        public static extern ref DateTime? ExpiresAt(BucketEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<FileCount>k__BackingField")]
        public static extern ref int FileCount(BucketEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<LastUsedAt>k__BackingField")]
        public static extern ref DateTime? LastUsedAt(BucketEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Name>k__BackingField")]
        public static extern ref string Name(BucketEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Owner>k__BackingField")]
        public static extern ref string Owner(BucketEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<OwnerKeyPrefix>k__BackingField")]
        public static extern ref string OwnerKeyPrefix(BucketEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<TotalSize>k__BackingField")]
        public static extern ref long TotalSize(BucketEntity @this);
    }
}
