// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using CarbonFiles.Infrastructure.Data.Entities;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal;
using Microsoft.EntityFrameworkCore.Storage;

#pragma warning disable 219, 612, 618
#nullable disable

namespace CarbonFiles.Infrastructure.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class BucketEntityEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "CarbonFiles.Infrastructure.Data.Entities.BucketEntity",
                typeof(BucketEntity),
                baseEntityType,
                propertyCount: 11,
                unnamedIndexCount: 3,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(string),
                propertyInfo: typeof(BucketEntity).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BucketEntity).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                maxLength: 10);
            id.SetGetter(
                string (BucketEntity instance) => BucketEntityUnsafeAccessors.Id(instance),
                bool (BucketEntity instance) => BucketEntityUnsafeAccessors.Id(instance) == null);
            id.SetSetter(
                BucketEntity (BucketEntity instance, string value) =>
                {
                    BucketEntityUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetMaterializationSetter(
                BucketEntity (BucketEntity instance, string value) =>
                {
                    BucketEntityUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetAccessors(
                string (IInternalEntry entry) => BucketEntityUnsafeAccessors.Id(((BucketEntity)(entry.Entity))),
                string (IInternalEntry entry) => BucketEntityUnsafeAccessors.Id(((BucketEntity)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(id, 0),
                string (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<string>(id, 0));
            id.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: -1);
            id.TypeMapping = SqliteStringTypeMapping.Default;
            id.SetCurrentValueComparer(new EntryCurrentValueComparer<string>(id));

            var createdAt = runtimeEntityType.AddProperty(
                "CreatedAt",
                typeof(DateTime),
                propertyInfo: typeof(BucketEntity).GetProperty("CreatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BucketEntity).GetField("<CreatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            createdAt.SetGetter(
                DateTime (BucketEntity instance) => BucketEntityUnsafeAccessors.CreatedAt(instance),
                bool (BucketEntity instance) => BucketEntityUnsafeAccessors.CreatedAt(instance) == default(DateTime));
            createdAt.SetSetter(
                BucketEntity (BucketEntity instance, DateTime value) =>
                {
                    BucketEntityUnsafeAccessors.CreatedAt(instance) = value;
                    return instance;
                });
            createdAt.SetMaterializationSetter(
                BucketEntity (BucketEntity instance, DateTime value) =>
                {
                    BucketEntityUnsafeAccessors.CreatedAt(instance) = value;
                    return instance;
                });
            createdAt.SetAccessors(
                DateTime (IInternalEntry entry) => BucketEntityUnsafeAccessors.CreatedAt(((BucketEntity)(entry.Entity))),
                DateTime (IInternalEntry entry) => BucketEntityUnsafeAccessors.CreatedAt(((BucketEntity)(entry.Entity))),
                DateTime (IInternalEntry entry) => entry.ReadOriginalValue<DateTime>(createdAt, 1),
                DateTime (IInternalEntry entry) => entry.GetCurrentValue<DateTime>(createdAt));
            createdAt.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            createdAt.TypeMapping = SqliteDateTimeTypeMapping.Default;

            var description = runtimeEntityType.AddProperty(
                "Description",
                typeof(string),
                propertyInfo: typeof(BucketEntity).GetProperty("Description", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BucketEntity).GetField("<Description>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 1000);
            description.SetGetter(
                string (BucketEntity instance) => BucketEntityUnsafeAccessors.Description(instance),
                bool (BucketEntity instance) => BucketEntityUnsafeAccessors.Description(instance) == null);
            description.SetSetter(
                BucketEntity (BucketEntity instance, string value) =>
                {
                    BucketEntityUnsafeAccessors.Description(instance) = value;
                    return instance;
                });
            description.SetMaterializationSetter(
                BucketEntity (BucketEntity instance, string value) =>
                {
                    BucketEntityUnsafeAccessors.Description(instance) = value;
                    return instance;
                });
            description.SetAccessors(
                string (IInternalEntry entry) => BucketEntityUnsafeAccessors.Description(((BucketEntity)(entry.Entity))),
                string (IInternalEntry entry) => BucketEntityUnsafeAccessors.Description(((BucketEntity)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(description, 2),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(description));
            description.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            description.TypeMapping = SqliteStringTypeMapping.Default;

            var downloadCount = runtimeEntityType.AddProperty(
                "DownloadCount",
                typeof(long),
                propertyInfo: typeof(BucketEntity).GetProperty("DownloadCount", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BucketEntity).GetField("<DownloadCount>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            downloadCount.SetGetter(
                long (BucketEntity instance) => BucketEntityUnsafeAccessors.DownloadCount(instance),
                bool (BucketEntity instance) => BucketEntityUnsafeAccessors.DownloadCount(instance) == 0L);
            downloadCount.SetSetter(
                BucketEntity (BucketEntity instance, long value) =>
                {
                    BucketEntityUnsafeAccessors.DownloadCount(instance) = value;
                    return instance;
                });
            downloadCount.SetMaterializationSetter(
                BucketEntity (BucketEntity instance, long value) =>
                {
                    BucketEntityUnsafeAccessors.DownloadCount(instance) = value;
                    return instance;
                });
            downloadCount.SetAccessors(
                long (IInternalEntry entry) => BucketEntityUnsafeAccessors.DownloadCount(((BucketEntity)(entry.Entity))),
                long (IInternalEntry entry) => BucketEntityUnsafeAccessors.DownloadCount(((BucketEntity)(entry.Entity))),
                long (IInternalEntry entry) => entry.ReadOriginalValue<long>(downloadCount, 3),
                long (IInternalEntry entry) => entry.GetCurrentValue<long>(downloadCount));
            downloadCount.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            downloadCount.TypeMapping = LongTypeMapping.Default.Clone(
                comparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                keyComparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                providerValueComparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));

            var expiresAt = runtimeEntityType.AddProperty(
                "ExpiresAt",
                typeof(DateTime?),
                propertyInfo: typeof(BucketEntity).GetProperty("ExpiresAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BucketEntity).GetField("<ExpiresAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            expiresAt.SetGetter(
                DateTime? (BucketEntity instance) => BucketEntityUnsafeAccessors.ExpiresAt(instance),
                bool (BucketEntity instance) => !(BucketEntityUnsafeAccessors.ExpiresAt(instance).HasValue));
            expiresAt.SetSetter(
                BucketEntity (BucketEntity instance, DateTime? value) =>
                {
                    BucketEntityUnsafeAccessors.ExpiresAt(instance) = value;
                    return instance;
                });
            expiresAt.SetMaterializationSetter(
                BucketEntity (BucketEntity instance, DateTime? value) =>
                {
                    BucketEntityUnsafeAccessors.ExpiresAt(instance) = value;
                    return instance;
                });
            expiresAt.SetAccessors(
                DateTime? (IInternalEntry entry) => BucketEntityUnsafeAccessors.ExpiresAt(((BucketEntity)(entry.Entity))),
                DateTime? (IInternalEntry entry) => BucketEntityUnsafeAccessors.ExpiresAt(((BucketEntity)(entry.Entity))),
                DateTime? (IInternalEntry entry) => entry.ReadOriginalValue<DateTime?>(expiresAt, 4),
                DateTime? (IInternalEntry entry) => entry.GetCurrentValue<DateTime?>(expiresAt));
            expiresAt.SetPropertyIndexes(
                index: 4,
                originalValueIndex: 4,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            expiresAt.TypeMapping = SqliteDateTimeTypeMapping.Default;
            expiresAt.SetComparer(new NullableValueComparer<DateTime>(expiresAt.TypeMapping.Comparer));
            expiresAt.SetKeyComparer(new NullableValueComparer<DateTime>(expiresAt.TypeMapping.KeyComparer));

            var fileCount = runtimeEntityType.AddProperty(
                "FileCount",
                typeof(int),
                propertyInfo: typeof(BucketEntity).GetProperty("FileCount", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BucketEntity).GetField("<FileCount>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            fileCount.SetGetter(
                int (BucketEntity instance) => BucketEntityUnsafeAccessors.FileCount(instance),
                bool (BucketEntity instance) => BucketEntityUnsafeAccessors.FileCount(instance) == 0);
            fileCount.SetSetter(
                BucketEntity (BucketEntity instance, int value) =>
                {
                    BucketEntityUnsafeAccessors.FileCount(instance) = value;
                    return instance;
                });
            fileCount.SetMaterializationSetter(
                BucketEntity (BucketEntity instance, int value) =>
                {
                    BucketEntityUnsafeAccessors.FileCount(instance) = value;
                    return instance;
                });
            fileCount.SetAccessors(
                int (IInternalEntry entry) => BucketEntityUnsafeAccessors.FileCount(((BucketEntity)(entry.Entity))),
                int (IInternalEntry entry) => BucketEntityUnsafeAccessors.FileCount(((BucketEntity)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(fileCount, 5),
                int (IInternalEntry entry) => entry.GetCurrentValue<int>(fileCount));
            fileCount.SetPropertyIndexes(
                index: 5,
                originalValueIndex: 5,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            fileCount.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));

            var lastUsedAt = runtimeEntityType.AddProperty(
                "LastUsedAt",
                typeof(DateTime?),
                propertyInfo: typeof(BucketEntity).GetProperty("LastUsedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BucketEntity).GetField("<LastUsedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            lastUsedAt.SetGetter(
                DateTime? (BucketEntity instance) => BucketEntityUnsafeAccessors.LastUsedAt(instance),
                bool (BucketEntity instance) => !(BucketEntityUnsafeAccessors.LastUsedAt(instance).HasValue));
            lastUsedAt.SetSetter(
                BucketEntity (BucketEntity instance, DateTime? value) =>
                {
                    BucketEntityUnsafeAccessors.LastUsedAt(instance) = value;
                    return instance;
                });
            lastUsedAt.SetMaterializationSetter(
                BucketEntity (BucketEntity instance, DateTime? value) =>
                {
                    BucketEntityUnsafeAccessors.LastUsedAt(instance) = value;
                    return instance;
                });
            lastUsedAt.SetAccessors(
                DateTime? (IInternalEntry entry) => BucketEntityUnsafeAccessors.LastUsedAt(((BucketEntity)(entry.Entity))),
                DateTime? (IInternalEntry entry) => BucketEntityUnsafeAccessors.LastUsedAt(((BucketEntity)(entry.Entity))),
                DateTime? (IInternalEntry entry) => entry.ReadOriginalValue<DateTime?>(lastUsedAt, 6),
                DateTime? (IInternalEntry entry) => entry.GetCurrentValue<DateTime?>(lastUsedAt));
            lastUsedAt.SetPropertyIndexes(
                index: 6,
                originalValueIndex: 6,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            lastUsedAt.TypeMapping = SqliteDateTimeTypeMapping.Default;
            lastUsedAt.SetComparer(new NullableValueComparer<DateTime>(lastUsedAt.TypeMapping.Comparer));
            lastUsedAt.SetKeyComparer(new NullableValueComparer<DateTime>(lastUsedAt.TypeMapping.KeyComparer));

            var name = runtimeEntityType.AddProperty(
                "Name",
                typeof(string),
                propertyInfo: typeof(BucketEntity).GetProperty("Name", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BucketEntity).GetField("<Name>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 255);
            name.SetGetter(
                string (BucketEntity instance) => BucketEntityUnsafeAccessors.Name(instance),
                bool (BucketEntity instance) => BucketEntityUnsafeAccessors.Name(instance) == null);
            name.SetSetter(
                BucketEntity (BucketEntity instance, string value) =>
                {
                    BucketEntityUnsafeAccessors.Name(instance) = value;
                    return instance;
                });
            name.SetMaterializationSetter(
                BucketEntity (BucketEntity instance, string value) =>
                {
                    BucketEntityUnsafeAccessors.Name(instance) = value;
                    return instance;
                });
            name.SetAccessors(
                string (IInternalEntry entry) => BucketEntityUnsafeAccessors.Name(((BucketEntity)(entry.Entity))),
                string (IInternalEntry entry) => BucketEntityUnsafeAccessors.Name(((BucketEntity)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(name, 7),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(name));
            name.SetPropertyIndexes(
                index: 7,
                originalValueIndex: 7,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            name.TypeMapping = SqliteStringTypeMapping.Default;

            var owner = runtimeEntityType.AddProperty(
                "Owner",
                typeof(string),
                propertyInfo: typeof(BucketEntity).GetProperty("Owner", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BucketEntity).GetField("<Owner>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 255);
            owner.SetGetter(
                string (BucketEntity instance) => BucketEntityUnsafeAccessors.Owner(instance),
                bool (BucketEntity instance) => BucketEntityUnsafeAccessors.Owner(instance) == null);
            owner.SetSetter(
                BucketEntity (BucketEntity instance, string value) =>
                {
                    BucketEntityUnsafeAccessors.Owner(instance) = value;
                    return instance;
                });
            owner.SetMaterializationSetter(
                BucketEntity (BucketEntity instance, string value) =>
                {
                    BucketEntityUnsafeAccessors.Owner(instance) = value;
                    return instance;
                });
            owner.SetAccessors(
                string (IInternalEntry entry) => BucketEntityUnsafeAccessors.Owner(((BucketEntity)(entry.Entity))),
                string (IInternalEntry entry) => BucketEntityUnsafeAccessors.Owner(((BucketEntity)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(owner, 8),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(owner));
            owner.SetPropertyIndexes(
                index: 8,
                originalValueIndex: 8,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            owner.TypeMapping = SqliteStringTypeMapping.Default;

            var ownerKeyPrefix = runtimeEntityType.AddProperty(
                "OwnerKeyPrefix",
                typeof(string),
                propertyInfo: typeof(BucketEntity).GetProperty("OwnerKeyPrefix", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BucketEntity).GetField("<OwnerKeyPrefix>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 13);
            ownerKeyPrefix.SetGetter(
                string (BucketEntity instance) => BucketEntityUnsafeAccessors.OwnerKeyPrefix(instance),
                bool (BucketEntity instance) => BucketEntityUnsafeAccessors.OwnerKeyPrefix(instance) == null);
            ownerKeyPrefix.SetSetter(
                BucketEntity (BucketEntity instance, string value) =>
                {
                    BucketEntityUnsafeAccessors.OwnerKeyPrefix(instance) = value;
                    return instance;
                });
            ownerKeyPrefix.SetMaterializationSetter(
                BucketEntity (BucketEntity instance, string value) =>
                {
                    BucketEntityUnsafeAccessors.OwnerKeyPrefix(instance) = value;
                    return instance;
                });
            ownerKeyPrefix.SetAccessors(
                string (IInternalEntry entry) => BucketEntityUnsafeAccessors.OwnerKeyPrefix(((BucketEntity)(entry.Entity))),
                string (IInternalEntry entry) => BucketEntityUnsafeAccessors.OwnerKeyPrefix(((BucketEntity)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(ownerKeyPrefix, 9),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(ownerKeyPrefix));
            ownerKeyPrefix.SetPropertyIndexes(
                index: 9,
                originalValueIndex: 9,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            ownerKeyPrefix.TypeMapping = SqliteStringTypeMapping.Default;

            var totalSize = runtimeEntityType.AddProperty(
                "TotalSize",
                typeof(long),
                propertyInfo: typeof(BucketEntity).GetProperty("TotalSize", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BucketEntity).GetField("<TotalSize>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            totalSize.SetGetter(
                long (BucketEntity instance) => BucketEntityUnsafeAccessors.TotalSize(instance),
                bool (BucketEntity instance) => BucketEntityUnsafeAccessors.TotalSize(instance) == 0L);
            totalSize.SetSetter(
                BucketEntity (BucketEntity instance, long value) =>
                {
                    BucketEntityUnsafeAccessors.TotalSize(instance) = value;
                    return instance;
                });
            totalSize.SetMaterializationSetter(
                BucketEntity (BucketEntity instance, long value) =>
                {
                    BucketEntityUnsafeAccessors.TotalSize(instance) = value;
                    return instance;
                });
            totalSize.SetAccessors(
                long (IInternalEntry entry) => BucketEntityUnsafeAccessors.TotalSize(((BucketEntity)(entry.Entity))),
                long (IInternalEntry entry) => BucketEntityUnsafeAccessors.TotalSize(((BucketEntity)(entry.Entity))),
                long (IInternalEntry entry) => entry.ReadOriginalValue<long>(totalSize, 10),
                long (IInternalEntry entry) => entry.GetCurrentValue<long>(totalSize));
            totalSize.SetPropertyIndexes(
                index: 10,
                originalValueIndex: 10,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            totalSize.TypeMapping = LongTypeMapping.Default.Clone(
                comparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                keyComparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                providerValueComparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { expiresAt });

            var index0 = runtimeEntityType.AddIndex(
                new[] { owner });

            var index1 = runtimeEntityType.AddIndex(
                new[] { ownerKeyPrefix });

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var id = runtimeEntityType.FindProperty("Id");
            var createdAt = runtimeEntityType.FindProperty("CreatedAt");
            var description = runtimeEntityType.FindProperty("Description");
            var downloadCount = runtimeEntityType.FindProperty("DownloadCount");
            var expiresAt = runtimeEntityType.FindProperty("ExpiresAt");
            var fileCount = runtimeEntityType.FindProperty("FileCount");
            var lastUsedAt = runtimeEntityType.FindProperty("LastUsedAt");
            var name = runtimeEntityType.FindProperty("Name");
            var owner = runtimeEntityType.FindProperty("Owner");
            var ownerKeyPrefix = runtimeEntityType.FindProperty("OwnerKeyPrefix");
            var totalSize = runtimeEntityType.FindProperty("TotalSize");
            var key = runtimeEntityType.FindKey(new[] { id });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNullableFactory<string, int>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<string>(key));
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((BucketEntity)(source.Entity));
                    return ((ISnapshot)(new Snapshot<string, DateTime, string, long, DateTime?, int, DateTime?, string, string, string, long>((source.GetCurrentValue<string>(id) == null ? null : ((ValueComparer<string>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(id))), ((ValueComparer<DateTime>)(((IProperty)createdAt).GetValueComparer())).Snapshot(source.GetCurrentValue<DateTime>(createdAt)), (source.GetCurrentValue<string>(description) == null ? null : ((ValueComparer<string>)(((IProperty)description).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(description))), ((ValueComparer<long>)(((IProperty)downloadCount).GetValueComparer())).Snapshot(source.GetCurrentValue<long>(downloadCount)), (source.GetCurrentValue<DateTime?>(expiresAt) == null ? null : ((ValueComparer<DateTime?>)(((IProperty)expiresAt).GetValueComparer())).Snapshot(source.GetCurrentValue<DateTime?>(expiresAt))), ((ValueComparer<int>)(((IProperty)fileCount).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(fileCount)), (source.GetCurrentValue<DateTime?>(lastUsedAt) == null ? null : ((ValueComparer<DateTime?>)(((IProperty)lastUsedAt).GetValueComparer())).Snapshot(source.GetCurrentValue<DateTime?>(lastUsedAt))), (source.GetCurrentValue<string>(name) == null ? null : ((ValueComparer<string>)(((IProperty)name).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(name))), (source.GetCurrentValue<string>(owner) == null ? null : ((ValueComparer<string>)(((IProperty)owner).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(owner))), (source.GetCurrentValue<string>(ownerKeyPrefix) == null ? null : ((ValueComparer<string>)(((IProperty)ownerKeyPrefix).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(ownerKeyPrefix))), ((ValueComparer<long>)(((IProperty)totalSize).GetValueComparer())).Snapshot(source.GetCurrentValue<long>(totalSize)))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => Snapshot.Empty);
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((BucketEntity)(source.Entity));
                    return ((ISnapshot)(new Snapshot<string>((source.GetCurrentValue<string>(id) == null ? null : ((ValueComparer<string>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<string>(id))))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 11,
                navigationCount: 0,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 11,
                shadowCount: 0,
                relationshipCount: 1,
                storeGeneratedCount: 0));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Buckets");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
