// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Update.Internal;

#pragma warning disable 219, 612, 618
#nullable disable

namespace CarbonFiles.Infrastructure.Data.CompiledModels
{
    public partial class CarbonFilesDbContextModel
    {
        private CarbonFilesDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("86deba0b-15db-4314-a814-e8b7677bcde1"), entityTypeCount: 5)
        {
        }

        partial void Initialize()
        {
            var apiKeyEntity = ApiKeyEntityEntityType.Create(this);
            var bucketEntity = BucketEntityEntityType.Create(this);
            var fileEntity = FileEntityEntityType.Create(this);
            var shortUrlEntity = ShortUrlEntityEntityType.Create(this);
            var uploadTokenEntity = UploadTokenEntityEntityType.Create(this);

            ApiKeyEntityEntityType.CreateAnnotations(apiKeyEntity);
            BucketEntityEntityType.CreateAnnotations(bucketEntity);
            FileEntityEntityType.CreateAnnotations(fileEntity);
            ShortUrlEntityEntityType.CreateAnnotations(shortUrlEntity);
            UploadTokenEntityEntityType.CreateAnnotations(uploadTokenEntity);

            AddAnnotation("ProductVersion", "10.0.3");
            AddRuntimeAnnotation("Relational:RelationalModelFactory", () => CreateRelationalModel());
        }

        private IRelationalModel CreateRelationalModel()
        {
            var relationalModel = new RelationalModel(this);

            var apiKeyEntity = FindEntityType("CarbonFiles.Infrastructure.Data.Entities.ApiKeyEntity")!;

            var defaultTableMappings = new List<TableMappingBase<ColumnMappingBase>>();
            apiKeyEntity.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings);
            var carbonFilesInfrastructureDataEntitiesApiKeyEntityTableBase = new TableBase("CarbonFiles.Infrastructure.Data.Entities.ApiKeyEntity", null, relationalModel);
            var createdAtColumnBase = new ColumnBase<ColumnMappingBase>("CreatedAt", "TEXT", carbonFilesInfrastructureDataEntitiesApiKeyEntityTableBase);
            carbonFilesInfrastructureDataEntitiesApiKeyEntityTableBase.Columns.Add("CreatedAt", createdAtColumnBase);
            var hashedSecretColumnBase = new ColumnBase<ColumnMappingBase>("HashedSecret", "TEXT", carbonFilesInfrastructureDataEntitiesApiKeyEntityTableBase);
            carbonFilesInfrastructureDataEntitiesApiKeyEntityTableBase.Columns.Add("HashedSecret", hashedSecretColumnBase);
            var lastUsedAtColumnBase = new ColumnBase<ColumnMappingBase>("LastUsedAt", "TEXT", carbonFilesInfrastructureDataEntitiesApiKeyEntityTableBase)
            {
                IsNullable = true
            };
            carbonFilesInfrastructureDataEntitiesApiKeyEntityTableBase.Columns.Add("LastUsedAt", lastUsedAtColumnBase);
            var nameColumnBase = new ColumnBase<ColumnMappingBase>("Name", "TEXT", carbonFilesInfrastructureDataEntitiesApiKeyEntityTableBase);
            carbonFilesInfrastructureDataEntitiesApiKeyEntityTableBase.Columns.Add("Name", nameColumnBase);
            var prefixColumnBase = new ColumnBase<ColumnMappingBase>("Prefix", "TEXT", carbonFilesInfrastructureDataEntitiesApiKeyEntityTableBase);
            carbonFilesInfrastructureDataEntitiesApiKeyEntityTableBase.Columns.Add("Prefix", prefixColumnBase);
            relationalModel.DefaultTables.Add("CarbonFiles.Infrastructure.Data.Entities.ApiKeyEntity", carbonFilesInfrastructureDataEntitiesApiKeyEntityTableBase);
            var carbonFilesInfrastructureDataEntitiesApiKeyEntityMappingBase = new TableMappingBase<ColumnMappingBase>(apiKeyEntity, carbonFilesInfrastructureDataEntitiesApiKeyEntityTableBase, null);
            carbonFilesInfrastructureDataEntitiesApiKeyEntityTableBase.AddTypeMapping(carbonFilesInfrastructureDataEntitiesApiKeyEntityMappingBase, false);
            defaultTableMappings.Add(carbonFilesInfrastructureDataEntitiesApiKeyEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)prefixColumnBase, apiKeyEntity.FindProperty("Prefix")!, carbonFilesInfrastructureDataEntitiesApiKeyEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)createdAtColumnBase, apiKeyEntity.FindProperty("CreatedAt")!, carbonFilesInfrastructureDataEntitiesApiKeyEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)hashedSecretColumnBase, apiKeyEntity.FindProperty("HashedSecret")!, carbonFilesInfrastructureDataEntitiesApiKeyEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)lastUsedAtColumnBase, apiKeyEntity.FindProperty("LastUsedAt")!, carbonFilesInfrastructureDataEntitiesApiKeyEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)nameColumnBase, apiKeyEntity.FindProperty("Name")!, carbonFilesInfrastructureDataEntitiesApiKeyEntityMappingBase);

            var tableMappings = new List<TableMapping>();
            apiKeyEntity.SetRuntimeAnnotation("Relational:TableMappings", tableMappings);
            var apiKeysTable = new Table("ApiKeys", null, relationalModel);
            var prefixColumn = new Column("Prefix", "TEXT", apiKeysTable);
            apiKeysTable.Columns.Add("Prefix", prefixColumn);
            prefixColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(prefixColumn);
            var createdAtColumn = new Column("CreatedAt", "TEXT", apiKeysTable);
            apiKeysTable.Columns.Add("CreatedAt", createdAtColumn);
            createdAtColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<DateTime>(createdAtColumn);
            var hashedSecretColumn = new Column("HashedSecret", "TEXT", apiKeysTable);
            apiKeysTable.Columns.Add("HashedSecret", hashedSecretColumn);
            hashedSecretColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(hashedSecretColumn);
            var lastUsedAtColumn = new Column("LastUsedAt", "TEXT", apiKeysTable)
            {
                IsNullable = true
            };
            apiKeysTable.Columns.Add("LastUsedAt", lastUsedAtColumn);
            lastUsedAtColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<DateTime>(lastUsedAtColumn);
            var nameColumn = new Column("Name", "TEXT", apiKeysTable);
            apiKeysTable.Columns.Add("Name", nameColumn);
            nameColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(nameColumn);
            relationalModel.Tables.Add(("ApiKeys", null), apiKeysTable);
            var apiKeysTableMapping = new TableMapping(apiKeyEntity, apiKeysTable, null);
            apiKeysTable.AddTypeMapping(apiKeysTableMapping, false);
            tableMappings.Add(apiKeysTableMapping);
            RelationalModel.CreateColumnMapping(prefixColumn, apiKeyEntity.FindProperty("Prefix")!, apiKeysTableMapping);
            RelationalModel.CreateColumnMapping(createdAtColumn, apiKeyEntity.FindProperty("CreatedAt")!, apiKeysTableMapping);
            RelationalModel.CreateColumnMapping(hashedSecretColumn, apiKeyEntity.FindProperty("HashedSecret")!, apiKeysTableMapping);
            RelationalModel.CreateColumnMapping(lastUsedAtColumn, apiKeyEntity.FindProperty("LastUsedAt")!, apiKeysTableMapping);
            RelationalModel.CreateColumnMapping(nameColumn, apiKeyEntity.FindProperty("Name")!, apiKeysTableMapping);
            var pK_ApiKeys = new UniqueConstraint("PK_ApiKeys", apiKeysTable, new[] { prefixColumn });
            apiKeysTable.PrimaryKey = pK_ApiKeys;
            pK_ApiKeys.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<string>(pK_ApiKeys));
            var pK_ApiKeysKey = RelationalModel.GetKey(this,
                "CarbonFiles.Infrastructure.Data.Entities.ApiKeyEntity",
                new[] { "Prefix" });
            pK_ApiKeys.MappedKeys.Add(pK_ApiKeysKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_ApiKeysKey).Add(pK_ApiKeys);
            apiKeysTable.UniqueConstraints.Add("PK_ApiKeys", pK_ApiKeys);

            var bucketEntity = FindEntityType("CarbonFiles.Infrastructure.Data.Entities.BucketEntity")!;

            var defaultTableMappings0 = new List<TableMappingBase<ColumnMappingBase>>();
            bucketEntity.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings0);
            var carbonFilesInfrastructureDataEntitiesBucketEntityTableBase = new TableBase("CarbonFiles.Infrastructure.Data.Entities.BucketEntity", null, relationalModel);
            var createdAtColumnBase0 = new ColumnBase<ColumnMappingBase>("CreatedAt", "TEXT", carbonFilesInfrastructureDataEntitiesBucketEntityTableBase);
            carbonFilesInfrastructureDataEntitiesBucketEntityTableBase.Columns.Add("CreatedAt", createdAtColumnBase0);
            var descriptionColumnBase = new ColumnBase<ColumnMappingBase>("Description", "TEXT", carbonFilesInfrastructureDataEntitiesBucketEntityTableBase)
            {
                IsNullable = true
            };
            carbonFilesInfrastructureDataEntitiesBucketEntityTableBase.Columns.Add("Description", descriptionColumnBase);
            var downloadCountColumnBase = new ColumnBase<ColumnMappingBase>("DownloadCount", "INTEGER", carbonFilesInfrastructureDataEntitiesBucketEntityTableBase);
            carbonFilesInfrastructureDataEntitiesBucketEntityTableBase.Columns.Add("DownloadCount", downloadCountColumnBase);
            var expiresAtColumnBase = new ColumnBase<ColumnMappingBase>("ExpiresAt", "TEXT", carbonFilesInfrastructureDataEntitiesBucketEntityTableBase)
            {
                IsNullable = true
            };
            carbonFilesInfrastructureDataEntitiesBucketEntityTableBase.Columns.Add("ExpiresAt", expiresAtColumnBase);
            var fileCountColumnBase = new ColumnBase<ColumnMappingBase>("FileCount", "INTEGER", carbonFilesInfrastructureDataEntitiesBucketEntityTableBase);
            carbonFilesInfrastructureDataEntitiesBucketEntityTableBase.Columns.Add("FileCount", fileCountColumnBase);
            var idColumnBase = new ColumnBase<ColumnMappingBase>("Id", "TEXT", carbonFilesInfrastructureDataEntitiesBucketEntityTableBase);
            carbonFilesInfrastructureDataEntitiesBucketEntityTableBase.Columns.Add("Id", idColumnBase);
            var lastUsedAtColumnBase0 = new ColumnBase<ColumnMappingBase>("LastUsedAt", "TEXT", carbonFilesInfrastructureDataEntitiesBucketEntityTableBase)
            {
                IsNullable = true
            };
            carbonFilesInfrastructureDataEntitiesBucketEntityTableBase.Columns.Add("LastUsedAt", lastUsedAtColumnBase0);
            var nameColumnBase0 = new ColumnBase<ColumnMappingBase>("Name", "TEXT", carbonFilesInfrastructureDataEntitiesBucketEntityTableBase);
            carbonFilesInfrastructureDataEntitiesBucketEntityTableBase.Columns.Add("Name", nameColumnBase0);
            var ownerColumnBase = new ColumnBase<ColumnMappingBase>("Owner", "TEXT", carbonFilesInfrastructureDataEntitiesBucketEntityTableBase);
            carbonFilesInfrastructureDataEntitiesBucketEntityTableBase.Columns.Add("Owner", ownerColumnBase);
            var ownerKeyPrefixColumnBase = new ColumnBase<ColumnMappingBase>("OwnerKeyPrefix", "TEXT", carbonFilesInfrastructureDataEntitiesBucketEntityTableBase)
            {
                IsNullable = true
            };
            carbonFilesInfrastructureDataEntitiesBucketEntityTableBase.Columns.Add("OwnerKeyPrefix", ownerKeyPrefixColumnBase);
            var totalSizeColumnBase = new ColumnBase<ColumnMappingBase>("TotalSize", "INTEGER", carbonFilesInfrastructureDataEntitiesBucketEntityTableBase);
            carbonFilesInfrastructureDataEntitiesBucketEntityTableBase.Columns.Add("TotalSize", totalSizeColumnBase);
            relationalModel.DefaultTables.Add("CarbonFiles.Infrastructure.Data.Entities.BucketEntity", carbonFilesInfrastructureDataEntitiesBucketEntityTableBase);
            var carbonFilesInfrastructureDataEntitiesBucketEntityMappingBase = new TableMappingBase<ColumnMappingBase>(bucketEntity, carbonFilesInfrastructureDataEntitiesBucketEntityTableBase, null);
            carbonFilesInfrastructureDataEntitiesBucketEntityTableBase.AddTypeMapping(carbonFilesInfrastructureDataEntitiesBucketEntityMappingBase, false);
            defaultTableMappings0.Add(carbonFilesInfrastructureDataEntitiesBucketEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase, bucketEntity.FindProperty("Id")!, carbonFilesInfrastructureDataEntitiesBucketEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)createdAtColumnBase0, bucketEntity.FindProperty("CreatedAt")!, carbonFilesInfrastructureDataEntitiesBucketEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)descriptionColumnBase, bucketEntity.FindProperty("Description")!, carbonFilesInfrastructureDataEntitiesBucketEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)downloadCountColumnBase, bucketEntity.FindProperty("DownloadCount")!, carbonFilesInfrastructureDataEntitiesBucketEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)expiresAtColumnBase, bucketEntity.FindProperty("ExpiresAt")!, carbonFilesInfrastructureDataEntitiesBucketEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)fileCountColumnBase, bucketEntity.FindProperty("FileCount")!, carbonFilesInfrastructureDataEntitiesBucketEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)lastUsedAtColumnBase0, bucketEntity.FindProperty("LastUsedAt")!, carbonFilesInfrastructureDataEntitiesBucketEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)nameColumnBase0, bucketEntity.FindProperty("Name")!, carbonFilesInfrastructureDataEntitiesBucketEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)ownerColumnBase, bucketEntity.FindProperty("Owner")!, carbonFilesInfrastructureDataEntitiesBucketEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)ownerKeyPrefixColumnBase, bucketEntity.FindProperty("OwnerKeyPrefix")!, carbonFilesInfrastructureDataEntitiesBucketEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)totalSizeColumnBase, bucketEntity.FindProperty("TotalSize")!, carbonFilesInfrastructureDataEntitiesBucketEntityMappingBase);

            var tableMappings0 = new List<TableMapping>();
            bucketEntity.SetRuntimeAnnotation("Relational:TableMappings", tableMappings0);
            var bucketsTable = new Table("Buckets", null, relationalModel);
            var idColumn = new Column("Id", "TEXT", bucketsTable);
            bucketsTable.Columns.Add("Id", idColumn);
            idColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(idColumn);
            var createdAtColumn0 = new Column("CreatedAt", "TEXT", bucketsTable);
            bucketsTable.Columns.Add("CreatedAt", createdAtColumn0);
            createdAtColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<DateTime>(createdAtColumn0);
            var descriptionColumn = new Column("Description", "TEXT", bucketsTable)
            {
                IsNullable = true
            };
            bucketsTable.Columns.Add("Description", descriptionColumn);
            descriptionColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(descriptionColumn);
            var downloadCountColumn = new Column("DownloadCount", "INTEGER", bucketsTable);
            bucketsTable.Columns.Add("DownloadCount", downloadCountColumn);
            downloadCountColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<long>(downloadCountColumn);
            var expiresAtColumn = new Column("ExpiresAt", "TEXT", bucketsTable)
            {
                IsNullable = true
            };
            bucketsTable.Columns.Add("ExpiresAt", expiresAtColumn);
            expiresAtColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<DateTime>(expiresAtColumn);
            var fileCountColumn = new Column("FileCount", "INTEGER", bucketsTable);
            bucketsTable.Columns.Add("FileCount", fileCountColumn);
            fileCountColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(fileCountColumn);
            var lastUsedAtColumn0 = new Column("LastUsedAt", "TEXT", bucketsTable)
            {
                IsNullable = true
            };
            bucketsTable.Columns.Add("LastUsedAt", lastUsedAtColumn0);
            lastUsedAtColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<DateTime>(lastUsedAtColumn0);
            var nameColumn0 = new Column("Name", "TEXT", bucketsTable);
            bucketsTable.Columns.Add("Name", nameColumn0);
            nameColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(nameColumn0);
            var ownerColumn = new Column("Owner", "TEXT", bucketsTable);
            bucketsTable.Columns.Add("Owner", ownerColumn);
            ownerColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(ownerColumn);
            var ownerKeyPrefixColumn = new Column("OwnerKeyPrefix", "TEXT", bucketsTable)
            {
                IsNullable = true
            };
            bucketsTable.Columns.Add("OwnerKeyPrefix", ownerKeyPrefixColumn);
            ownerKeyPrefixColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(ownerKeyPrefixColumn);
            var totalSizeColumn = new Column("TotalSize", "INTEGER", bucketsTable);
            bucketsTable.Columns.Add("TotalSize", totalSizeColumn);
            totalSizeColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<long>(totalSizeColumn);
            relationalModel.Tables.Add(("Buckets", null), bucketsTable);
            var bucketsTableMapping = new TableMapping(bucketEntity, bucketsTable, null);
            bucketsTable.AddTypeMapping(bucketsTableMapping, false);
            tableMappings0.Add(bucketsTableMapping);
            RelationalModel.CreateColumnMapping(idColumn, bucketEntity.FindProperty("Id")!, bucketsTableMapping);
            RelationalModel.CreateColumnMapping(createdAtColumn0, bucketEntity.FindProperty("CreatedAt")!, bucketsTableMapping);
            RelationalModel.CreateColumnMapping(descriptionColumn, bucketEntity.FindProperty("Description")!, bucketsTableMapping);
            RelationalModel.CreateColumnMapping(downloadCountColumn, bucketEntity.FindProperty("DownloadCount")!, bucketsTableMapping);
            RelationalModel.CreateColumnMapping(expiresAtColumn, bucketEntity.FindProperty("ExpiresAt")!, bucketsTableMapping);
            RelationalModel.CreateColumnMapping(fileCountColumn, bucketEntity.FindProperty("FileCount")!, bucketsTableMapping);
            RelationalModel.CreateColumnMapping(lastUsedAtColumn0, bucketEntity.FindProperty("LastUsedAt")!, bucketsTableMapping);
            RelationalModel.CreateColumnMapping(nameColumn0, bucketEntity.FindProperty("Name")!, bucketsTableMapping);
            RelationalModel.CreateColumnMapping(ownerColumn, bucketEntity.FindProperty("Owner")!, bucketsTableMapping);
            RelationalModel.CreateColumnMapping(ownerKeyPrefixColumn, bucketEntity.FindProperty("OwnerKeyPrefix")!, bucketsTableMapping);
            RelationalModel.CreateColumnMapping(totalSizeColumn, bucketEntity.FindProperty("TotalSize")!, bucketsTableMapping);
            var pK_Buckets = new UniqueConstraint("PK_Buckets", bucketsTable, new[] { idColumn });
            bucketsTable.PrimaryKey = pK_Buckets;
            pK_Buckets.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<string>(pK_Buckets));
            var pK_BucketsKey = RelationalModel.GetKey(this,
                "CarbonFiles.Infrastructure.Data.Entities.BucketEntity",
                new[] { "Id" });
            pK_Buckets.MappedKeys.Add(pK_BucketsKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_BucketsKey).Add(pK_Buckets);
            bucketsTable.UniqueConstraints.Add("PK_Buckets", pK_Buckets);
            var iX_Buckets_ExpiresAt = new TableIndex(
            "IX_Buckets_ExpiresAt", bucketsTable, new[] { expiresAtColumn }, false);
            iX_Buckets_ExpiresAt.SetRowIndexValueFactory(new SimpleRowIndexValueFactory<DateTime>(iX_Buckets_ExpiresAt));
            var iX_Buckets_ExpiresAtIx = RelationalModel.GetIndex(this,
                "CarbonFiles.Infrastructure.Data.Entities.BucketEntity",
                new[] { "ExpiresAt" });
            iX_Buckets_ExpiresAt.MappedIndexes.Add(iX_Buckets_ExpiresAtIx);
            RelationalModel.GetOrCreateTableIndexes(iX_Buckets_ExpiresAtIx).Add(iX_Buckets_ExpiresAt);
            bucketsTable.Indexes.Add("IX_Buckets_ExpiresAt", iX_Buckets_ExpiresAt);
            var iX_Buckets_Owner = new TableIndex(
            "IX_Buckets_Owner", bucketsTable, new[] { ownerColumn }, false);
            iX_Buckets_Owner.SetRowIndexValueFactory(new SimpleRowIndexValueFactory<string>(iX_Buckets_Owner));
            var iX_Buckets_OwnerIx = RelationalModel.GetIndex(this,
                "CarbonFiles.Infrastructure.Data.Entities.BucketEntity",
                new[] { "Owner" });
            iX_Buckets_Owner.MappedIndexes.Add(iX_Buckets_OwnerIx);
            RelationalModel.GetOrCreateTableIndexes(iX_Buckets_OwnerIx).Add(iX_Buckets_Owner);
            bucketsTable.Indexes.Add("IX_Buckets_Owner", iX_Buckets_Owner);
            var iX_Buckets_OwnerKeyPrefix = new TableIndex(
            "IX_Buckets_OwnerKeyPrefix", bucketsTable, new[] { ownerKeyPrefixColumn }, false);
            iX_Buckets_OwnerKeyPrefix.SetRowIndexValueFactory(new SimpleRowIndexValueFactory<string>(iX_Buckets_OwnerKeyPrefix));
            var iX_Buckets_OwnerKeyPrefixIx = RelationalModel.GetIndex(this,
                "CarbonFiles.Infrastructure.Data.Entities.BucketEntity",
                new[] { "OwnerKeyPrefix" });
            iX_Buckets_OwnerKeyPrefix.MappedIndexes.Add(iX_Buckets_OwnerKeyPrefixIx);
            RelationalModel.GetOrCreateTableIndexes(iX_Buckets_OwnerKeyPrefixIx).Add(iX_Buckets_OwnerKeyPrefix);
            bucketsTable.Indexes.Add("IX_Buckets_OwnerKeyPrefix", iX_Buckets_OwnerKeyPrefix);

            var fileEntity = FindEntityType("CarbonFiles.Infrastructure.Data.Entities.FileEntity")!;

            var defaultTableMappings1 = new List<TableMappingBase<ColumnMappingBase>>();
            fileEntity.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings1);
            var carbonFilesInfrastructureDataEntitiesFileEntityTableBase = new TableBase("CarbonFiles.Infrastructure.Data.Entities.FileEntity", null, relationalModel);
            var bucketIdColumnBase = new ColumnBase<ColumnMappingBase>("BucketId", "TEXT", carbonFilesInfrastructureDataEntitiesFileEntityTableBase);
            carbonFilesInfrastructureDataEntitiesFileEntityTableBase.Columns.Add("BucketId", bucketIdColumnBase);
            var createdAtColumnBase1 = new ColumnBase<ColumnMappingBase>("CreatedAt", "TEXT", carbonFilesInfrastructureDataEntitiesFileEntityTableBase);
            carbonFilesInfrastructureDataEntitiesFileEntityTableBase.Columns.Add("CreatedAt", createdAtColumnBase1);
            var mimeTypeColumnBase = new ColumnBase<ColumnMappingBase>("MimeType", "TEXT", carbonFilesInfrastructureDataEntitiesFileEntityTableBase);
            carbonFilesInfrastructureDataEntitiesFileEntityTableBase.Columns.Add("MimeType", mimeTypeColumnBase);
            var nameColumnBase1 = new ColumnBase<ColumnMappingBase>("Name", "TEXT", carbonFilesInfrastructureDataEntitiesFileEntityTableBase);
            carbonFilesInfrastructureDataEntitiesFileEntityTableBase.Columns.Add("Name", nameColumnBase1);
            var pathColumnBase = new ColumnBase<ColumnMappingBase>("Path", "TEXT", carbonFilesInfrastructureDataEntitiesFileEntityTableBase);
            carbonFilesInfrastructureDataEntitiesFileEntityTableBase.Columns.Add("Path", pathColumnBase);
            var shortCodeColumnBase = new ColumnBase<ColumnMappingBase>("ShortCode", "TEXT", carbonFilesInfrastructureDataEntitiesFileEntityTableBase)
            {
                IsNullable = true
            };
            carbonFilesInfrastructureDataEntitiesFileEntityTableBase.Columns.Add("ShortCode", shortCodeColumnBase);
            var sizeColumnBase = new ColumnBase<ColumnMappingBase>("Size", "INTEGER", carbonFilesInfrastructureDataEntitiesFileEntityTableBase);
            carbonFilesInfrastructureDataEntitiesFileEntityTableBase.Columns.Add("Size", sizeColumnBase);
            var updatedAtColumnBase = new ColumnBase<ColumnMappingBase>("UpdatedAt", "TEXT", carbonFilesInfrastructureDataEntitiesFileEntityTableBase);
            carbonFilesInfrastructureDataEntitiesFileEntityTableBase.Columns.Add("UpdatedAt", updatedAtColumnBase);
            relationalModel.DefaultTables.Add("CarbonFiles.Infrastructure.Data.Entities.FileEntity", carbonFilesInfrastructureDataEntitiesFileEntityTableBase);
            var carbonFilesInfrastructureDataEntitiesFileEntityMappingBase = new TableMappingBase<ColumnMappingBase>(fileEntity, carbonFilesInfrastructureDataEntitiesFileEntityTableBase, null);
            carbonFilesInfrastructureDataEntitiesFileEntityTableBase.AddTypeMapping(carbonFilesInfrastructureDataEntitiesFileEntityMappingBase, false);
            defaultTableMappings1.Add(carbonFilesInfrastructureDataEntitiesFileEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)bucketIdColumnBase, fileEntity.FindProperty("BucketId")!, carbonFilesInfrastructureDataEntitiesFileEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)pathColumnBase, fileEntity.FindProperty("Path")!, carbonFilesInfrastructureDataEntitiesFileEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)createdAtColumnBase1, fileEntity.FindProperty("CreatedAt")!, carbonFilesInfrastructureDataEntitiesFileEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)mimeTypeColumnBase, fileEntity.FindProperty("MimeType")!, carbonFilesInfrastructureDataEntitiesFileEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)nameColumnBase1, fileEntity.FindProperty("Name")!, carbonFilesInfrastructureDataEntitiesFileEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)shortCodeColumnBase, fileEntity.FindProperty("ShortCode")!, carbonFilesInfrastructureDataEntitiesFileEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)sizeColumnBase, fileEntity.FindProperty("Size")!, carbonFilesInfrastructureDataEntitiesFileEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)updatedAtColumnBase, fileEntity.FindProperty("UpdatedAt")!, carbonFilesInfrastructureDataEntitiesFileEntityMappingBase);

            var tableMappings1 = new List<TableMapping>();
            fileEntity.SetRuntimeAnnotation("Relational:TableMappings", tableMappings1);
            var filesTable = new Table("Files", null, relationalModel);
            var bucketIdColumn = new Column("BucketId", "TEXT", filesTable);
            filesTable.Columns.Add("BucketId", bucketIdColumn);
            bucketIdColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(bucketIdColumn);
            var pathColumn = new Column("Path", "TEXT", filesTable);
            filesTable.Columns.Add("Path", pathColumn);
            pathColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(pathColumn);
            var createdAtColumn1 = new Column("CreatedAt", "TEXT", filesTable);
            filesTable.Columns.Add("CreatedAt", createdAtColumn1);
            createdAtColumn1.Accessors = ColumnAccessorsFactory.CreateGeneric<DateTime>(createdAtColumn1);
            var mimeTypeColumn = new Column("MimeType", "TEXT", filesTable);
            filesTable.Columns.Add("MimeType", mimeTypeColumn);
            mimeTypeColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(mimeTypeColumn);
            var nameColumn1 = new Column("Name", "TEXT", filesTable);
            filesTable.Columns.Add("Name", nameColumn1);
            nameColumn1.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(nameColumn1);
            var shortCodeColumn = new Column("ShortCode", "TEXT", filesTable)
            {
                IsNullable = true
            };
            filesTable.Columns.Add("ShortCode", shortCodeColumn);
            shortCodeColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(shortCodeColumn);
            var sizeColumn = new Column("Size", "INTEGER", filesTable);
            filesTable.Columns.Add("Size", sizeColumn);
            sizeColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<long>(sizeColumn);
            var updatedAtColumn = new Column("UpdatedAt", "TEXT", filesTable);
            filesTable.Columns.Add("UpdatedAt", updatedAtColumn);
            updatedAtColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<DateTime>(updatedAtColumn);
            relationalModel.Tables.Add(("Files", null), filesTable);
            var filesTableMapping = new TableMapping(fileEntity, filesTable, null);
            filesTable.AddTypeMapping(filesTableMapping, false);
            tableMappings1.Add(filesTableMapping);
            RelationalModel.CreateColumnMapping(bucketIdColumn, fileEntity.FindProperty("BucketId")!, filesTableMapping);
            RelationalModel.CreateColumnMapping(pathColumn, fileEntity.FindProperty("Path")!, filesTableMapping);
            RelationalModel.CreateColumnMapping(createdAtColumn1, fileEntity.FindProperty("CreatedAt")!, filesTableMapping);
            RelationalModel.CreateColumnMapping(mimeTypeColumn, fileEntity.FindProperty("MimeType")!, filesTableMapping);
            RelationalModel.CreateColumnMapping(nameColumn1, fileEntity.FindProperty("Name")!, filesTableMapping);
            RelationalModel.CreateColumnMapping(shortCodeColumn, fileEntity.FindProperty("ShortCode")!, filesTableMapping);
            RelationalModel.CreateColumnMapping(sizeColumn, fileEntity.FindProperty("Size")!, filesTableMapping);
            RelationalModel.CreateColumnMapping(updatedAtColumn, fileEntity.FindProperty("UpdatedAt")!, filesTableMapping);
            var pK_Files = new UniqueConstraint("PK_Files", filesTable, new[] { bucketIdColumn, pathColumn });
            filesTable.PrimaryKey = pK_Files;
            pK_Files.SetRowKeyValueFactory(new CompositeRowKeyValueFactory(pK_Files));
            var pK_FilesKey = RelationalModel.GetKey(this,
                "CarbonFiles.Infrastructure.Data.Entities.FileEntity",
                new[] { "BucketId", "Path" });
            pK_Files.MappedKeys.Add(pK_FilesKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_FilesKey).Add(pK_Files);
            filesTable.UniqueConstraints.Add("PK_Files", pK_Files);
            var iX_Files_BucketId = new TableIndex(
            "IX_Files_BucketId", filesTable, new[] { bucketIdColumn }, false);
            iX_Files_BucketId.SetRowIndexValueFactory(new SimpleRowIndexValueFactory<string>(iX_Files_BucketId));
            var iX_Files_BucketIdIx = RelationalModel.GetIndex(this,
                "CarbonFiles.Infrastructure.Data.Entities.FileEntity",
                new[] { "BucketId" });
            iX_Files_BucketId.MappedIndexes.Add(iX_Files_BucketIdIx);
            RelationalModel.GetOrCreateTableIndexes(iX_Files_BucketIdIx).Add(iX_Files_BucketId);
            filesTable.Indexes.Add("IX_Files_BucketId", iX_Files_BucketId);
            var iX_Files_ShortCode = new TableIndex(
            "IX_Files_ShortCode", filesTable, new[] { shortCodeColumn }, true);
            iX_Files_ShortCode.SetRowIndexValueFactory(new SimpleRowIndexValueFactory<string>(iX_Files_ShortCode));
            var iX_Files_ShortCodeIx = RelationalModel.GetIndex(this,
                "CarbonFiles.Infrastructure.Data.Entities.FileEntity",
                new[] { "ShortCode" });
            iX_Files_ShortCode.MappedIndexes.Add(iX_Files_ShortCodeIx);
            RelationalModel.GetOrCreateTableIndexes(iX_Files_ShortCodeIx).Add(iX_Files_ShortCode);
            filesTable.Indexes.Add("IX_Files_ShortCode", iX_Files_ShortCode);

            var shortUrlEntity = FindEntityType("CarbonFiles.Infrastructure.Data.Entities.ShortUrlEntity")!;

            var defaultTableMappings2 = new List<TableMappingBase<ColumnMappingBase>>();
            shortUrlEntity.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings2);
            var carbonFilesInfrastructureDataEntitiesShortUrlEntityTableBase = new TableBase("CarbonFiles.Infrastructure.Data.Entities.ShortUrlEntity", null, relationalModel);
            var bucketIdColumnBase0 = new ColumnBase<ColumnMappingBase>("BucketId", "TEXT", carbonFilesInfrastructureDataEntitiesShortUrlEntityTableBase);
            carbonFilesInfrastructureDataEntitiesShortUrlEntityTableBase.Columns.Add("BucketId", bucketIdColumnBase0);
            var codeColumnBase = new ColumnBase<ColumnMappingBase>("Code", "TEXT", carbonFilesInfrastructureDataEntitiesShortUrlEntityTableBase);
            carbonFilesInfrastructureDataEntitiesShortUrlEntityTableBase.Columns.Add("Code", codeColumnBase);
            var createdAtColumnBase2 = new ColumnBase<ColumnMappingBase>("CreatedAt", "TEXT", carbonFilesInfrastructureDataEntitiesShortUrlEntityTableBase);
            carbonFilesInfrastructureDataEntitiesShortUrlEntityTableBase.Columns.Add("CreatedAt", createdAtColumnBase2);
            var filePathColumnBase = new ColumnBase<ColumnMappingBase>("FilePath", "TEXT", carbonFilesInfrastructureDataEntitiesShortUrlEntityTableBase);
            carbonFilesInfrastructureDataEntitiesShortUrlEntityTableBase.Columns.Add("FilePath", filePathColumnBase);
            relationalModel.DefaultTables.Add("CarbonFiles.Infrastructure.Data.Entities.ShortUrlEntity", carbonFilesInfrastructureDataEntitiesShortUrlEntityTableBase);
            var carbonFilesInfrastructureDataEntitiesShortUrlEntityMappingBase = new TableMappingBase<ColumnMappingBase>(shortUrlEntity, carbonFilesInfrastructureDataEntitiesShortUrlEntityTableBase, null);
            carbonFilesInfrastructureDataEntitiesShortUrlEntityTableBase.AddTypeMapping(carbonFilesInfrastructureDataEntitiesShortUrlEntityMappingBase, false);
            defaultTableMappings2.Add(carbonFilesInfrastructureDataEntitiesShortUrlEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)codeColumnBase, shortUrlEntity.FindProperty("Code")!, carbonFilesInfrastructureDataEntitiesShortUrlEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)bucketIdColumnBase0, shortUrlEntity.FindProperty("BucketId")!, carbonFilesInfrastructureDataEntitiesShortUrlEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)createdAtColumnBase2, shortUrlEntity.FindProperty("CreatedAt")!, carbonFilesInfrastructureDataEntitiesShortUrlEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)filePathColumnBase, shortUrlEntity.FindProperty("FilePath")!, carbonFilesInfrastructureDataEntitiesShortUrlEntityMappingBase);

            var tableMappings2 = new List<TableMapping>();
            shortUrlEntity.SetRuntimeAnnotation("Relational:TableMappings", tableMappings2);
            var shortUrlsTable = new Table("ShortUrls", null, relationalModel);
            var codeColumn = new Column("Code", "TEXT", shortUrlsTable);
            shortUrlsTable.Columns.Add("Code", codeColumn);
            codeColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(codeColumn);
            var bucketIdColumn0 = new Column("BucketId", "TEXT", shortUrlsTable);
            shortUrlsTable.Columns.Add("BucketId", bucketIdColumn0);
            bucketIdColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(bucketIdColumn0);
            var createdAtColumn2 = new Column("CreatedAt", "TEXT", shortUrlsTable);
            shortUrlsTable.Columns.Add("CreatedAt", createdAtColumn2);
            createdAtColumn2.Accessors = ColumnAccessorsFactory.CreateGeneric<DateTime>(createdAtColumn2);
            var filePathColumn = new Column("FilePath", "TEXT", shortUrlsTable);
            shortUrlsTable.Columns.Add("FilePath", filePathColumn);
            filePathColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(filePathColumn);
            relationalModel.Tables.Add(("ShortUrls", null), shortUrlsTable);
            var shortUrlsTableMapping = new TableMapping(shortUrlEntity, shortUrlsTable, null);
            shortUrlsTable.AddTypeMapping(shortUrlsTableMapping, false);
            tableMappings2.Add(shortUrlsTableMapping);
            RelationalModel.CreateColumnMapping(codeColumn, shortUrlEntity.FindProperty("Code")!, shortUrlsTableMapping);
            RelationalModel.CreateColumnMapping(bucketIdColumn0, shortUrlEntity.FindProperty("BucketId")!, shortUrlsTableMapping);
            RelationalModel.CreateColumnMapping(createdAtColumn2, shortUrlEntity.FindProperty("CreatedAt")!, shortUrlsTableMapping);
            RelationalModel.CreateColumnMapping(filePathColumn, shortUrlEntity.FindProperty("FilePath")!, shortUrlsTableMapping);
            var pK_ShortUrls = new UniqueConstraint("PK_ShortUrls", shortUrlsTable, new[] { codeColumn });
            shortUrlsTable.PrimaryKey = pK_ShortUrls;
            pK_ShortUrls.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<string>(pK_ShortUrls));
            var pK_ShortUrlsKey = RelationalModel.GetKey(this,
                "CarbonFiles.Infrastructure.Data.Entities.ShortUrlEntity",
                new[] { "Code" });
            pK_ShortUrls.MappedKeys.Add(pK_ShortUrlsKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_ShortUrlsKey).Add(pK_ShortUrls);
            shortUrlsTable.UniqueConstraints.Add("PK_ShortUrls", pK_ShortUrls);
            var iX_ShortUrls_BucketId_FilePath = new TableIndex(
            "IX_ShortUrls_BucketId_FilePath", shortUrlsTable, new[] { bucketIdColumn0, filePathColumn }, false);
            iX_ShortUrls_BucketId_FilePath.SetRowIndexValueFactory(new CompositeRowIndexValueFactory(iX_ShortUrls_BucketId_FilePath));
            var iX_ShortUrls_BucketId_FilePathIx = RelationalModel.GetIndex(this,
                "CarbonFiles.Infrastructure.Data.Entities.ShortUrlEntity",
                new[] { "BucketId", "FilePath" });
            iX_ShortUrls_BucketId_FilePath.MappedIndexes.Add(iX_ShortUrls_BucketId_FilePathIx);
            RelationalModel.GetOrCreateTableIndexes(iX_ShortUrls_BucketId_FilePathIx).Add(iX_ShortUrls_BucketId_FilePath);
            shortUrlsTable.Indexes.Add("IX_ShortUrls_BucketId_FilePath", iX_ShortUrls_BucketId_FilePath);

            var uploadTokenEntity = FindEntityType("CarbonFiles.Infrastructure.Data.Entities.UploadTokenEntity")!;

            var defaultTableMappings3 = new List<TableMappingBase<ColumnMappingBase>>();
            uploadTokenEntity.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings3);
            var carbonFilesInfrastructureDataEntitiesUploadTokenEntityTableBase = new TableBase("CarbonFiles.Infrastructure.Data.Entities.UploadTokenEntity", null, relationalModel);
            var bucketIdColumnBase1 = new ColumnBase<ColumnMappingBase>("BucketId", "TEXT", carbonFilesInfrastructureDataEntitiesUploadTokenEntityTableBase);
            carbonFilesInfrastructureDataEntitiesUploadTokenEntityTableBase.Columns.Add("BucketId", bucketIdColumnBase1);
            var createdAtColumnBase3 = new ColumnBase<ColumnMappingBase>("CreatedAt", "TEXT", carbonFilesInfrastructureDataEntitiesUploadTokenEntityTableBase);
            carbonFilesInfrastructureDataEntitiesUploadTokenEntityTableBase.Columns.Add("CreatedAt", createdAtColumnBase3);
            var expiresAtColumnBase0 = new ColumnBase<ColumnMappingBase>("ExpiresAt", "TEXT", carbonFilesInfrastructureDataEntitiesUploadTokenEntityTableBase);
            carbonFilesInfrastructureDataEntitiesUploadTokenEntityTableBase.Columns.Add("ExpiresAt", expiresAtColumnBase0);
            var maxUploadsColumnBase = new ColumnBase<ColumnMappingBase>("MaxUploads", "INTEGER", carbonFilesInfrastructureDataEntitiesUploadTokenEntityTableBase)
            {
                IsNullable = true
            };
            carbonFilesInfrastructureDataEntitiesUploadTokenEntityTableBase.Columns.Add("MaxUploads", maxUploadsColumnBase);
            var tokenColumnBase = new ColumnBase<ColumnMappingBase>("Token", "TEXT", carbonFilesInfrastructureDataEntitiesUploadTokenEntityTableBase);
            carbonFilesInfrastructureDataEntitiesUploadTokenEntityTableBase.Columns.Add("Token", tokenColumnBase);
            var uploadsUsedColumnBase = new ColumnBase<ColumnMappingBase>("UploadsUsed", "INTEGER", carbonFilesInfrastructureDataEntitiesUploadTokenEntityTableBase);
            carbonFilesInfrastructureDataEntitiesUploadTokenEntityTableBase.Columns.Add("UploadsUsed", uploadsUsedColumnBase);
            relationalModel.DefaultTables.Add("CarbonFiles.Infrastructure.Data.Entities.UploadTokenEntity", carbonFilesInfrastructureDataEntitiesUploadTokenEntityTableBase);
            var carbonFilesInfrastructureDataEntitiesUploadTokenEntityMappingBase = new TableMappingBase<ColumnMappingBase>(uploadTokenEntity, carbonFilesInfrastructureDataEntitiesUploadTokenEntityTableBase, null);
            carbonFilesInfrastructureDataEntitiesUploadTokenEntityTableBase.AddTypeMapping(carbonFilesInfrastructureDataEntitiesUploadTokenEntityMappingBase, false);
            defaultTableMappings3.Add(carbonFilesInfrastructureDataEntitiesUploadTokenEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)tokenColumnBase, uploadTokenEntity.FindProperty("Token")!, carbonFilesInfrastructureDataEntitiesUploadTokenEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)bucketIdColumnBase1, uploadTokenEntity.FindProperty("BucketId")!, carbonFilesInfrastructureDataEntitiesUploadTokenEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)createdAtColumnBase3, uploadTokenEntity.FindProperty("CreatedAt")!, carbonFilesInfrastructureDataEntitiesUploadTokenEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)expiresAtColumnBase0, uploadTokenEntity.FindProperty("ExpiresAt")!, carbonFilesInfrastructureDataEntitiesUploadTokenEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)maxUploadsColumnBase, uploadTokenEntity.FindProperty("MaxUploads")!, carbonFilesInfrastructureDataEntitiesUploadTokenEntityMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)uploadsUsedColumnBase, uploadTokenEntity.FindProperty("UploadsUsed")!, carbonFilesInfrastructureDataEntitiesUploadTokenEntityMappingBase);

            var tableMappings3 = new List<TableMapping>();
            uploadTokenEntity.SetRuntimeAnnotation("Relational:TableMappings", tableMappings3);
            var uploadTokensTable = new Table("UploadTokens", null, relationalModel);
            var tokenColumn = new Column("Token", "TEXT", uploadTokensTable);
            uploadTokensTable.Columns.Add("Token", tokenColumn);
            tokenColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(tokenColumn);
            var bucketIdColumn1 = new Column("BucketId", "TEXT", uploadTokensTable);
            uploadTokensTable.Columns.Add("BucketId", bucketIdColumn1);
            bucketIdColumn1.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(bucketIdColumn1);
            var createdAtColumn3 = new Column("CreatedAt", "TEXT", uploadTokensTable);
            uploadTokensTable.Columns.Add("CreatedAt", createdAtColumn3);
            createdAtColumn3.Accessors = ColumnAccessorsFactory.CreateGeneric<DateTime>(createdAtColumn3);
            var expiresAtColumn0 = new Column("ExpiresAt", "TEXT", uploadTokensTable);
            uploadTokensTable.Columns.Add("ExpiresAt", expiresAtColumn0);
            expiresAtColumn0.Accessors = ColumnAccessorsFactory.CreateGeneric<DateTime>(expiresAtColumn0);
            var maxUploadsColumn = new Column("MaxUploads", "INTEGER", uploadTokensTable)
            {
                IsNullable = true
            };
            uploadTokensTable.Columns.Add("MaxUploads", maxUploadsColumn);
            maxUploadsColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(maxUploadsColumn);
            var uploadsUsedColumn = new Column("UploadsUsed", "INTEGER", uploadTokensTable);
            uploadTokensTable.Columns.Add("UploadsUsed", uploadsUsedColumn);
            uploadsUsedColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(uploadsUsedColumn);
            relationalModel.Tables.Add(("UploadTokens", null), uploadTokensTable);
            var uploadTokensTableMapping = new TableMapping(uploadTokenEntity, uploadTokensTable, null);
            uploadTokensTable.AddTypeMapping(uploadTokensTableMapping, false);
            tableMappings3.Add(uploadTokensTableMapping);
            RelationalModel.CreateColumnMapping(tokenColumn, uploadTokenEntity.FindProperty("Token")!, uploadTokensTableMapping);
            RelationalModel.CreateColumnMapping(bucketIdColumn1, uploadTokenEntity.FindProperty("BucketId")!, uploadTokensTableMapping);
            RelationalModel.CreateColumnMapping(createdAtColumn3, uploadTokenEntity.FindProperty("CreatedAt")!, uploadTokensTableMapping);
            RelationalModel.CreateColumnMapping(expiresAtColumn0, uploadTokenEntity.FindProperty("ExpiresAt")!, uploadTokensTableMapping);
            RelationalModel.CreateColumnMapping(maxUploadsColumn, uploadTokenEntity.FindProperty("MaxUploads")!, uploadTokensTableMapping);
            RelationalModel.CreateColumnMapping(uploadsUsedColumn, uploadTokenEntity.FindProperty("UploadsUsed")!, uploadTokensTableMapping);
            var pK_UploadTokens = new UniqueConstraint("PK_UploadTokens", uploadTokensTable, new[] { tokenColumn });
            uploadTokensTable.PrimaryKey = pK_UploadTokens;
            pK_UploadTokens.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<string>(pK_UploadTokens));
            var pK_UploadTokensKey = RelationalModel.GetKey(this,
                "CarbonFiles.Infrastructure.Data.Entities.UploadTokenEntity",
                new[] { "Token" });
            pK_UploadTokens.MappedKeys.Add(pK_UploadTokensKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_UploadTokensKey).Add(pK_UploadTokens);
            uploadTokensTable.UniqueConstraints.Add("PK_UploadTokens", pK_UploadTokens);
            var iX_UploadTokens_BucketId = new TableIndex(
            "IX_UploadTokens_BucketId", uploadTokensTable, new[] { bucketIdColumn1 }, false);
            iX_UploadTokens_BucketId.SetRowIndexValueFactory(new SimpleRowIndexValueFactory<string>(iX_UploadTokens_BucketId));
            var iX_UploadTokens_BucketIdIx = RelationalModel.GetIndex(this,
                "CarbonFiles.Infrastructure.Data.Entities.UploadTokenEntity",
                new[] { "BucketId" });
            iX_UploadTokens_BucketId.MappedIndexes.Add(iX_UploadTokens_BucketIdIx);
            RelationalModel.GetOrCreateTableIndexes(iX_UploadTokens_BucketIdIx).Add(iX_UploadTokens_BucketId);
            uploadTokensTable.Indexes.Add("IX_UploadTokens_BucketId", iX_UploadTokens_BucketId);
            return relationalModel.MakeReadOnly();
        }
    }
}
