// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace CarbonFiles.Infrastructure.Data.CompiledModels
{
    public partial class CarbonFilesDbContextModel
    {
        private CarbonFilesDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("0391e2d3-1bf2-485e-a102-367e25131233"), entityTypeCount: 5)
        {
        }

        partial void Initialize()
        {
            var apiKeyEntity = ApiKeyEntityEntityType.Create(this);
            var bucketEntity = BucketEntityEntityType.Create(this);
            var fileEntity = FileEntityEntityType.Create(this);
            var shortUrlEntity = ShortUrlEntityEntityType.Create(this);
            var uploadTokenEntity = UploadTokenEntityEntityType.Create(this);

            ApiKeyEntityEntityType.CreateAnnotations(apiKeyEntity);
            BucketEntityEntityType.CreateAnnotations(bucketEntity);
            FileEntityEntityType.CreateAnnotations(fileEntity);
            ShortUrlEntityEntityType.CreateAnnotations(shortUrlEntity);
            UploadTokenEntityEntityType.CreateAnnotations(uploadTokenEntity);

            AddAnnotation("ProductVersion", "10.0.3");
        }
    }
}
