// <auto-generated />
using CarbonFiles.Infrastructure.Data;
using CarbonFiles.Infrastructure.Data.CompiledModels;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(CarbonFilesDbContext), typeof(CarbonFilesDbContextModel))]
