// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using CarbonFiles.Infrastructure.Data.Entities;

#pragma warning disable 219, 612, 618
#nullable disable

namespace CarbonFiles.Infrastructure.Data.CompiledModels
{
    public static class FileEntityUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<BucketId>k__BackingField")]
        public static extern ref string BucketId(FileEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Path>k__BackingField")]
        public static extern ref string Path(FileEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedAt>k__BackingField")]
        public static extern ref DateTime CreatedAt(FileEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<MimeType>k__BackingField")]
        public static extern ref string MimeType(FileEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Name>k__BackingField")]
        public static extern ref string Name(FileEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ShortCode>k__BackingField")]
        public static extern ref string ShortCode(FileEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Size>k__BackingField")]
        public static extern ref long Size(FileEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<UpdatedAt>k__BackingField")]
        public static extern ref DateTime UpdatedAt(FileEntity @this);
    }
}
