// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using CarbonFiles.Infrastructure.Data.Entities;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal;
using Microsoft.EntityFrameworkCore.Storage;

#pragma warning disable 219, 612, 618
#nullable disable

namespace CarbonFiles.Infrastructure.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class FileEntityEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "CarbonFiles.Infrastructure.Data.Entities.FileEntity",
                typeof(FileEntity),
                baseEntityType,
                propertyCount: 8,
                unnamedIndexCount: 2,
                keyCount: 1);

            var bucketId = runtimeEntityType.AddProperty(
                "BucketId",
                typeof(string),
                propertyInfo: typeof(FileEntity).GetProperty("BucketId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FileEntity).GetField("<BucketId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                maxLength: 10);
            bucketId.SetGetter(
                string (FileEntity instance) => FileEntityUnsafeAccessors.BucketId(instance),
                bool (FileEntity instance) => FileEntityUnsafeAccessors.BucketId(instance) == null);
            bucketId.SetSetter(
                FileEntity (FileEntity instance, string value) =>
                {
                    FileEntityUnsafeAccessors.BucketId(instance) = value;
                    return instance;
                });
            bucketId.SetMaterializationSetter(
                FileEntity (FileEntity instance, string value) =>
                {
                    FileEntityUnsafeAccessors.BucketId(instance) = value;
                    return instance;
                });
            bucketId.SetAccessors(
                string (IInternalEntry entry) => FileEntityUnsafeAccessors.BucketId(((FileEntity)(entry.Entity))),
                string (IInternalEntry entry) => FileEntityUnsafeAccessors.BucketId(((FileEntity)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(bucketId, 0),
                string (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<string>(bucketId, 0));
            bucketId.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: -1);
            bucketId.TypeMapping = SqliteStringTypeMapping.Default;
            bucketId.SetCurrentValueComparer(new EntryCurrentValueComparer<string>(bucketId));

            var path = runtimeEntityType.AddProperty(
                "Path",
                typeof(string),
                propertyInfo: typeof(FileEntity).GetProperty("Path", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FileEntity).GetField("<Path>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                maxLength: 1024);
            path.SetGetter(
                string (FileEntity instance) => FileEntityUnsafeAccessors.Path(instance),
                bool (FileEntity instance) => FileEntityUnsafeAccessors.Path(instance) == null);
            path.SetSetter(
                FileEntity (FileEntity instance, string value) =>
                {
                    FileEntityUnsafeAccessors.Path(instance) = value;
                    return instance;
                });
            path.SetMaterializationSetter(
                FileEntity (FileEntity instance, string value) =>
                {
                    FileEntityUnsafeAccessors.Path(instance) = value;
                    return instance;
                });
            path.SetAccessors(
                string (IInternalEntry entry) => FileEntityUnsafeAccessors.Path(((FileEntity)(entry.Entity))),
                string (IInternalEntry entry) => FileEntityUnsafeAccessors.Path(((FileEntity)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(path, 1),
                string (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<string>(path, 1));
            path.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: 1,
                storeGenerationIndex: -1);
            path.TypeMapping = SqliteStringTypeMapping.Default;
            path.SetCurrentValueComparer(new EntryCurrentValueComparer<string>(path));

            var createdAt = runtimeEntityType.AddProperty(
                "CreatedAt",
                typeof(DateTime),
                propertyInfo: typeof(FileEntity).GetProperty("CreatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FileEntity).GetField("<CreatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            createdAt.SetGetter(
                DateTime (FileEntity instance) => FileEntityUnsafeAccessors.CreatedAt(instance),
                bool (FileEntity instance) => FileEntityUnsafeAccessors.CreatedAt(instance) == default(DateTime));
            createdAt.SetSetter(
                FileEntity (FileEntity instance, DateTime value) =>
                {
                    FileEntityUnsafeAccessors.CreatedAt(instance) = value;
                    return instance;
                });
            createdAt.SetMaterializationSetter(
                FileEntity (FileEntity instance, DateTime value) =>
                {
                    FileEntityUnsafeAccessors.CreatedAt(instance) = value;
                    return instance;
                });
            createdAt.SetAccessors(
                DateTime (IInternalEntry entry) => FileEntityUnsafeAccessors.CreatedAt(((FileEntity)(entry.Entity))),
                DateTime (IInternalEntry entry) => FileEntityUnsafeAccessors.CreatedAt(((FileEntity)(entry.Entity))),
                DateTime (IInternalEntry entry) => entry.ReadOriginalValue<DateTime>(createdAt, 2),
                DateTime (IInternalEntry entry) => entry.GetCurrentValue<DateTime>(createdAt));
            createdAt.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            createdAt.TypeMapping = SqliteDateTimeTypeMapping.Default;

            var mimeType = runtimeEntityType.AddProperty(
                "MimeType",
                typeof(string),
                propertyInfo: typeof(FileEntity).GetProperty("MimeType", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FileEntity).GetField("<MimeType>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 255);
            mimeType.SetGetter(
                string (FileEntity instance) => FileEntityUnsafeAccessors.MimeType(instance),
                bool (FileEntity instance) => FileEntityUnsafeAccessors.MimeType(instance) == null);
            mimeType.SetSetter(
                FileEntity (FileEntity instance, string value) =>
                {
                    FileEntityUnsafeAccessors.MimeType(instance) = value;
                    return instance;
                });
            mimeType.SetMaterializationSetter(
                FileEntity (FileEntity instance, string value) =>
                {
                    FileEntityUnsafeAccessors.MimeType(instance) = value;
                    return instance;
                });
            mimeType.SetAccessors(
                string (IInternalEntry entry) => FileEntityUnsafeAccessors.MimeType(((FileEntity)(entry.Entity))),
                string (IInternalEntry entry) => FileEntityUnsafeAccessors.MimeType(((FileEntity)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(mimeType, 3),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(mimeType));
            mimeType.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            mimeType.TypeMapping = SqliteStringTypeMapping.Default;

            var name = runtimeEntityType.AddProperty(
                "Name",
                typeof(string),
                propertyInfo: typeof(FileEntity).GetProperty("Name", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FileEntity).GetField("<Name>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 255);
            name.SetGetter(
                string (FileEntity instance) => FileEntityUnsafeAccessors.Name(instance),
                bool (FileEntity instance) => FileEntityUnsafeAccessors.Name(instance) == null);
            name.SetSetter(
                FileEntity (FileEntity instance, string value) =>
                {
                    FileEntityUnsafeAccessors.Name(instance) = value;
                    return instance;
                });
            name.SetMaterializationSetter(
                FileEntity (FileEntity instance, string value) =>
                {
                    FileEntityUnsafeAccessors.Name(instance) = value;
                    return instance;
                });
            name.SetAccessors(
                string (IInternalEntry entry) => FileEntityUnsafeAccessors.Name(((FileEntity)(entry.Entity))),
                string (IInternalEntry entry) => FileEntityUnsafeAccessors.Name(((FileEntity)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(name, 4),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(name));
            name.SetPropertyIndexes(
                index: 4,
                originalValueIndex: 4,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            name.TypeMapping = SqliteStringTypeMapping.Default;

            var shortCode = runtimeEntityType.AddProperty(
                "ShortCode",
                typeof(string),
                propertyInfo: typeof(FileEntity).GetProperty("ShortCode", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FileEntity).GetField("<ShortCode>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 6);
            shortCode.SetGetter(
                string (FileEntity instance) => FileEntityUnsafeAccessors.ShortCode(instance),
                bool (FileEntity instance) => FileEntityUnsafeAccessors.ShortCode(instance) == null);
            shortCode.SetSetter(
                FileEntity (FileEntity instance, string value) =>
                {
                    FileEntityUnsafeAccessors.ShortCode(instance) = value;
                    return instance;
                });
            shortCode.SetMaterializationSetter(
                FileEntity (FileEntity instance, string value) =>
                {
                    FileEntityUnsafeAccessors.ShortCode(instance) = value;
                    return instance;
                });
            shortCode.SetAccessors(
                string (IInternalEntry entry) => FileEntityUnsafeAccessors.ShortCode(((FileEntity)(entry.Entity))),
                string (IInternalEntry entry) => FileEntityUnsafeAccessors.ShortCode(((FileEntity)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(shortCode, 5),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(shortCode));
            shortCode.SetPropertyIndexes(
                index: 5,
                originalValueIndex: 5,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            shortCode.TypeMapping = SqliteStringTypeMapping.Default;
            shortCode.SetCurrentValueComparer(new EntryCurrentValueComparer<string>(shortCode));

            var size = runtimeEntityType.AddProperty(
                "Size",
                typeof(long),
                propertyInfo: typeof(FileEntity).GetProperty("Size", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FileEntity).GetField("<Size>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            size.SetGetter(
                long (FileEntity instance) => FileEntityUnsafeAccessors.Size(instance),
                bool (FileEntity instance) => FileEntityUnsafeAccessors.Size(instance) == 0L);
            size.SetSetter(
                FileEntity (FileEntity instance, long value) =>
                {
                    FileEntityUnsafeAccessors.Size(instance) = value;
                    return instance;
                });
            size.SetMaterializationSetter(
                FileEntity (FileEntity instance, long value) =>
                {
                    FileEntityUnsafeAccessors.Size(instance) = value;
                    return instance;
                });
            size.SetAccessors(
                long (IInternalEntry entry) => FileEntityUnsafeAccessors.Size(((FileEntity)(entry.Entity))),
                long (IInternalEntry entry) => FileEntityUnsafeAccessors.Size(((FileEntity)(entry.Entity))),
                long (IInternalEntry entry) => entry.ReadOriginalValue<long>(size, 6),
                long (IInternalEntry entry) => entry.GetCurrentValue<long>(size));
            size.SetPropertyIndexes(
                index: 6,
                originalValueIndex: 6,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            size.TypeMapping = LongTypeMapping.Default.Clone(
                comparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                keyComparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                providerValueComparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));

            var updatedAt = runtimeEntityType.AddProperty(
                "UpdatedAt",
                typeof(DateTime),
                propertyInfo: typeof(FileEntity).GetProperty("UpdatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(FileEntity).GetField("<UpdatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            updatedAt.SetGetter(
                DateTime (FileEntity instance) => FileEntityUnsafeAccessors.UpdatedAt(instance),
                bool (FileEntity instance) => FileEntityUnsafeAccessors.UpdatedAt(instance) == default(DateTime));
            updatedAt.SetSetter(
                FileEntity (FileEntity instance, DateTime value) =>
                {
                    FileEntityUnsafeAccessors.UpdatedAt(instance) = value;
                    return instance;
                });
            updatedAt.SetMaterializationSetter(
                FileEntity (FileEntity instance, DateTime value) =>
                {
                    FileEntityUnsafeAccessors.UpdatedAt(instance) = value;
                    return instance;
                });
            updatedAt.SetAccessors(
                DateTime (IInternalEntry entry) => FileEntityUnsafeAccessors.UpdatedAt(((FileEntity)(entry.Entity))),
                DateTime (IInternalEntry entry) => FileEntityUnsafeAccessors.UpdatedAt(((FileEntity)(entry.Entity))),
                DateTime (IInternalEntry entry) => entry.ReadOriginalValue<DateTime>(updatedAt, 7),
                DateTime (IInternalEntry entry) => entry.GetCurrentValue<DateTime>(updatedAt));
            updatedAt.SetPropertyIndexes(
                index: 7,
                originalValueIndex: 7,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            updatedAt.TypeMapping = SqliteDateTimeTypeMapping.Default;

            var key = runtimeEntityType.AddKey(
                new[] { bucketId, path });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { bucketId });

            var index0 = runtimeEntityType.AddIndex(
                new[] { shortCode },
                unique: true);
            index0.AddAnnotation("Relational:Filter", "ShortCode IS NOT NULL");

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var bucketId = runtimeEntityType.FindProperty("BucketId");
            var path = runtimeEntityType.FindProperty("Path");
            var createdAt = runtimeEntityType.FindProperty("CreatedAt");
            var mimeType = runtimeEntityType.FindProperty("MimeType");
            var name = runtimeEntityType.FindProperty("Name");
            var shortCode = runtimeEntityType.FindProperty("ShortCode");
            var size = runtimeEntityType.FindProperty("Size");
            var updatedAt = runtimeEntityType.FindProperty("UpdatedAt");
            var key = runtimeEntityType.FindKey(new[] { bucketId, path });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateCompositeFactory(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<IReadOnlyList<object>>(key));
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((FileEntity)(source.Entity));
                    return ((ISnapshot)(new Snapshot<string, string, DateTime, string, string, string, long, DateTime>((source.GetCurrentValue<string>(bucketId) == null ? null : ((ValueComparer<string>)(((IProperty)bucketId).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(bucketId))), (source.GetCurrentValue<string>(path) == null ? null : ((ValueComparer<string>)(((IProperty)path).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(path))), ((ValueComparer<DateTime>)(((IProperty)createdAt).GetValueComparer())).Snapshot(source.GetCurrentValue<DateTime>(createdAt)), (source.GetCurrentValue<string>(mimeType) == null ? null : ((ValueComparer<string>)(((IProperty)mimeType).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(mimeType))), (source.GetCurrentValue<string>(name) == null ? null : ((ValueComparer<string>)(((IProperty)name).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(name))), (source.GetCurrentValue<string>(shortCode) == null ? null : ((ValueComparer<string>)(((IProperty)shortCode).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(shortCode))), ((ValueComparer<long>)(((IProperty)size).GetValueComparer())).Snapshot(source.GetCurrentValue<long>(size)), ((ValueComparer<DateTime>)(((IProperty)updatedAt).GetValueComparer())).Snapshot(source.GetCurrentValue<DateTime>(updatedAt)))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => Snapshot.Empty);
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((FileEntity)(source.Entity));
                    return ((ISnapshot)(new Snapshot<string, string>((source.GetCurrentValue<string>(bucketId) == null ? null : ((ValueComparer<string>)(((IProperty)bucketId).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<string>(bucketId))), (source.GetCurrentValue<string>(path) == null ? null : ((ValueComparer<string>)(((IProperty)path).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<string>(path))))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 8,
                navigationCount: 0,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 8,
                shadowCount: 0,
                relationshipCount: 2,
                storeGeneratedCount: 0));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Files");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
