// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using CarbonFiles.Infrastructure.Data.Entities;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal;

#pragma warning disable 219, 612, 618
#nullable disable

namespace CarbonFiles.Infrastructure.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class ShortUrlEntityEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "CarbonFiles.Infrastructure.Data.Entities.ShortUrlEntity",
                typeof(ShortUrlEntity),
                baseEntityType,
                propertyCount: 4,
                unnamedIndexCount: 1,
                keyCount: 1);

            var code = runtimeEntityType.AddProperty(
                "Code",
                typeof(string),
                propertyInfo: typeof(ShortUrlEntity).GetProperty("Code", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ShortUrlEntity).GetField("<Code>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                maxLength: 6);
            code.SetGetter(
                string (ShortUrlEntity instance) => ShortUrlEntityUnsafeAccessors.Code(instance),
                bool (ShortUrlEntity instance) => ShortUrlEntityUnsafeAccessors.Code(instance) == null);
            code.SetSetter(
                ShortUrlEntity (ShortUrlEntity instance, string value) =>
                {
                    ShortUrlEntityUnsafeAccessors.Code(instance) = value;
                    return instance;
                });
            code.SetMaterializationSetter(
                ShortUrlEntity (ShortUrlEntity instance, string value) =>
                {
                    ShortUrlEntityUnsafeAccessors.Code(instance) = value;
                    return instance;
                });
            code.SetAccessors(
                string (IInternalEntry entry) => ShortUrlEntityUnsafeAccessors.Code(((ShortUrlEntity)(entry.Entity))),
                string (IInternalEntry entry) => ShortUrlEntityUnsafeAccessors.Code(((ShortUrlEntity)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(code, 0),
                string (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<string>(code, 0));
            code.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: -1);
            code.TypeMapping = SqliteStringTypeMapping.Default;
            code.SetCurrentValueComparer(new EntryCurrentValueComparer<string>(code));

            var bucketId = runtimeEntityType.AddProperty(
                "BucketId",
                typeof(string),
                propertyInfo: typeof(ShortUrlEntity).GetProperty("BucketId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ShortUrlEntity).GetField("<BucketId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 10);
            bucketId.SetGetter(
                string (ShortUrlEntity instance) => ShortUrlEntityUnsafeAccessors.BucketId(instance),
                bool (ShortUrlEntity instance) => ShortUrlEntityUnsafeAccessors.BucketId(instance) == null);
            bucketId.SetSetter(
                ShortUrlEntity (ShortUrlEntity instance, string value) =>
                {
                    ShortUrlEntityUnsafeAccessors.BucketId(instance) = value;
                    return instance;
                });
            bucketId.SetMaterializationSetter(
                ShortUrlEntity (ShortUrlEntity instance, string value) =>
                {
                    ShortUrlEntityUnsafeAccessors.BucketId(instance) = value;
                    return instance;
                });
            bucketId.SetAccessors(
                string (IInternalEntry entry) => ShortUrlEntityUnsafeAccessors.BucketId(((ShortUrlEntity)(entry.Entity))),
                string (IInternalEntry entry) => ShortUrlEntityUnsafeAccessors.BucketId(((ShortUrlEntity)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(bucketId, 1),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(bucketId));
            bucketId.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            bucketId.TypeMapping = SqliteStringTypeMapping.Default;

            var createdAt = runtimeEntityType.AddProperty(
                "CreatedAt",
                typeof(DateTime),
                propertyInfo: typeof(ShortUrlEntity).GetProperty("CreatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ShortUrlEntity).GetField("<CreatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            createdAt.SetGetter(
                DateTime (ShortUrlEntity instance) => ShortUrlEntityUnsafeAccessors.CreatedAt(instance),
                bool (ShortUrlEntity instance) => ShortUrlEntityUnsafeAccessors.CreatedAt(instance) == default(DateTime));
            createdAt.SetSetter(
                ShortUrlEntity (ShortUrlEntity instance, DateTime value) =>
                {
                    ShortUrlEntityUnsafeAccessors.CreatedAt(instance) = value;
                    return instance;
                });
            createdAt.SetMaterializationSetter(
                ShortUrlEntity (ShortUrlEntity instance, DateTime value) =>
                {
                    ShortUrlEntityUnsafeAccessors.CreatedAt(instance) = value;
                    return instance;
                });
            createdAt.SetAccessors(
                DateTime (IInternalEntry entry) => ShortUrlEntityUnsafeAccessors.CreatedAt(((ShortUrlEntity)(entry.Entity))),
                DateTime (IInternalEntry entry) => ShortUrlEntityUnsafeAccessors.CreatedAt(((ShortUrlEntity)(entry.Entity))),
                DateTime (IInternalEntry entry) => entry.ReadOriginalValue<DateTime>(createdAt, 2),
                DateTime (IInternalEntry entry) => entry.GetCurrentValue<DateTime>(createdAt));
            createdAt.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            createdAt.TypeMapping = SqliteDateTimeTypeMapping.Default;

            var filePath = runtimeEntityType.AddProperty(
                "FilePath",
                typeof(string),
                propertyInfo: typeof(ShortUrlEntity).GetProperty("FilePath", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ShortUrlEntity).GetField("<FilePath>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 1024);
            filePath.SetGetter(
                string (ShortUrlEntity instance) => ShortUrlEntityUnsafeAccessors.FilePath(instance),
                bool (ShortUrlEntity instance) => ShortUrlEntityUnsafeAccessors.FilePath(instance) == null);
            filePath.SetSetter(
                ShortUrlEntity (ShortUrlEntity instance, string value) =>
                {
                    ShortUrlEntityUnsafeAccessors.FilePath(instance) = value;
                    return instance;
                });
            filePath.SetMaterializationSetter(
                ShortUrlEntity (ShortUrlEntity instance, string value) =>
                {
                    ShortUrlEntityUnsafeAccessors.FilePath(instance) = value;
                    return instance;
                });
            filePath.SetAccessors(
                string (IInternalEntry entry) => ShortUrlEntityUnsafeAccessors.FilePath(((ShortUrlEntity)(entry.Entity))),
                string (IInternalEntry entry) => ShortUrlEntityUnsafeAccessors.FilePath(((ShortUrlEntity)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(filePath, 3),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(filePath));
            filePath.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            filePath.TypeMapping = SqliteStringTypeMapping.Default;

            var key = runtimeEntityType.AddKey(
                new[] { code });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { bucketId, filePath });

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var code = runtimeEntityType.FindProperty("Code");
            var bucketId = runtimeEntityType.FindProperty("BucketId");
            var createdAt = runtimeEntityType.FindProperty("CreatedAt");
            var filePath = runtimeEntityType.FindProperty("FilePath");
            var key = runtimeEntityType.FindKey(new[] { code });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNullableFactory<string, int>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<string>(key));
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((ShortUrlEntity)(source.Entity));
                    return ((ISnapshot)(new Snapshot<string, string, DateTime, string>((source.GetCurrentValue<string>(code) == null ? null : ((ValueComparer<string>)(((IProperty)code).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(code))), (source.GetCurrentValue<string>(bucketId) == null ? null : ((ValueComparer<string>)(((IProperty)bucketId).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(bucketId))), ((ValueComparer<DateTime>)(((IProperty)createdAt).GetValueComparer())).Snapshot(source.GetCurrentValue<DateTime>(createdAt)), (source.GetCurrentValue<string>(filePath) == null ? null : ((ValueComparer<string>)(((IProperty)filePath).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(filePath))))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => Snapshot.Empty);
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((ShortUrlEntity)(source.Entity));
                    return ((ISnapshot)(new Snapshot<string>((source.GetCurrentValue<string>(code) == null ? null : ((ValueComparer<string>)(((IProperty)code).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<string>(code))))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 4,
                navigationCount: 0,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 4,
                shadowCount: 0,
                relationshipCount: 1,
                storeGeneratedCount: 0));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "ShortUrls");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
