// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using CarbonFiles.Infrastructure.Data.Entities;

#pragma warning disable 219, 612, 618
#nullable disable

namespace CarbonFiles.Infrastructure.Data.CompiledModels
{
    public static class ShortUrlEntityUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Code>k__BackingField")]
        public static extern ref string Code(ShortUrlEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<BucketId>k__BackingField")]
        public static extern ref string BucketId(ShortUrlEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedAt>k__BackingField")]
        public static extern ref DateTime CreatedAt(ShortUrlEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<FilePath>k__BackingField")]
        public static extern ref string FilePath(ShortUrlEntity @this);
    }
}
