// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using CarbonFiles.Infrastructure.Data.Entities;

#pragma warning disable 219, 612, 618
#nullable disable

namespace CarbonFiles.Infrastructure.Data.CompiledModels
{
    public static class UploadTokenEntityUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Token>k__BackingField")]
        public static extern ref string Token(UploadTokenEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<BucketId>k__BackingField")]
        public static extern ref string BucketId(UploadTokenEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedAt>k__BackingField")]
        public static extern ref DateTime CreatedAt(UploadTokenEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ExpiresAt>k__BackingField")]
        public static extern ref DateTime ExpiresAt(UploadTokenEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<MaxUploads>k__BackingField")]
        public static extern ref int? MaxUploads(UploadTokenEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<UploadsUsed>k__BackingField")]
        public static extern ref int UploadsUsed(UploadTokenEntity @this);
    }
}
