// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using CarbonFiles.Infrastructure.Data.Entities;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal;
using Microsoft.EntityFrameworkCore.Storage;

#pragma warning disable 219, 612, 618
#nullable disable

namespace CarbonFiles.Infrastructure.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class UploadTokenEntityEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "CarbonFiles.Infrastructure.Data.Entities.UploadTokenEntity",
                typeof(UploadTokenEntity),
                baseEntityType,
                propertyCount: 6,
                unnamedIndexCount: 1,
                keyCount: 1);

            var token = runtimeEntityType.AddProperty(
                "Token",
                typeof(string),
                propertyInfo: typeof(UploadTokenEntity).GetProperty("Token", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UploadTokenEntity).GetField("<Token>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                maxLength: 55);
            token.SetGetter(
                string (UploadTokenEntity instance) => UploadTokenEntityUnsafeAccessors.Token(instance),
                bool (UploadTokenEntity instance) => UploadTokenEntityUnsafeAccessors.Token(instance) == null);
            token.SetSetter(
                UploadTokenEntity (UploadTokenEntity instance, string value) =>
                {
                    UploadTokenEntityUnsafeAccessors.Token(instance) = value;
                    return instance;
                });
            token.SetMaterializationSetter(
                UploadTokenEntity (UploadTokenEntity instance, string value) =>
                {
                    UploadTokenEntityUnsafeAccessors.Token(instance) = value;
                    return instance;
                });
            token.SetAccessors(
                string (IInternalEntry entry) => UploadTokenEntityUnsafeAccessors.Token(((UploadTokenEntity)(entry.Entity))),
                string (IInternalEntry entry) => UploadTokenEntityUnsafeAccessors.Token(((UploadTokenEntity)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(token, 0),
                string (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<string>(token, 0));
            token.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: -1);
            token.TypeMapping = SqliteStringTypeMapping.Default;
            token.SetCurrentValueComparer(new EntryCurrentValueComparer<string>(token));

            var bucketId = runtimeEntityType.AddProperty(
                "BucketId",
                typeof(string),
                propertyInfo: typeof(UploadTokenEntity).GetProperty("BucketId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UploadTokenEntity).GetField("<BucketId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 10);
            bucketId.SetGetter(
                string (UploadTokenEntity instance) => UploadTokenEntityUnsafeAccessors.BucketId(instance),
                bool (UploadTokenEntity instance) => UploadTokenEntityUnsafeAccessors.BucketId(instance) == null);
            bucketId.SetSetter(
                UploadTokenEntity (UploadTokenEntity instance, string value) =>
                {
                    UploadTokenEntityUnsafeAccessors.BucketId(instance) = value;
                    return instance;
                });
            bucketId.SetMaterializationSetter(
                UploadTokenEntity (UploadTokenEntity instance, string value) =>
                {
                    UploadTokenEntityUnsafeAccessors.BucketId(instance) = value;
                    return instance;
                });
            bucketId.SetAccessors(
                string (IInternalEntry entry) => UploadTokenEntityUnsafeAccessors.BucketId(((UploadTokenEntity)(entry.Entity))),
                string (IInternalEntry entry) => UploadTokenEntityUnsafeAccessors.BucketId(((UploadTokenEntity)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(bucketId, 1),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(bucketId));
            bucketId.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            bucketId.TypeMapping = SqliteStringTypeMapping.Default;

            var createdAt = runtimeEntityType.AddProperty(
                "CreatedAt",
                typeof(DateTime),
                propertyInfo: typeof(UploadTokenEntity).GetProperty("CreatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UploadTokenEntity).GetField("<CreatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            createdAt.SetGetter(
                DateTime (UploadTokenEntity instance) => UploadTokenEntityUnsafeAccessors.CreatedAt(instance),
                bool (UploadTokenEntity instance) => UploadTokenEntityUnsafeAccessors.CreatedAt(instance) == default(DateTime));
            createdAt.SetSetter(
                UploadTokenEntity (UploadTokenEntity instance, DateTime value) =>
                {
                    UploadTokenEntityUnsafeAccessors.CreatedAt(instance) = value;
                    return instance;
                });
            createdAt.SetMaterializationSetter(
                UploadTokenEntity (UploadTokenEntity instance, DateTime value) =>
                {
                    UploadTokenEntityUnsafeAccessors.CreatedAt(instance) = value;
                    return instance;
                });
            createdAt.SetAccessors(
                DateTime (IInternalEntry entry) => UploadTokenEntityUnsafeAccessors.CreatedAt(((UploadTokenEntity)(entry.Entity))),
                DateTime (IInternalEntry entry) => UploadTokenEntityUnsafeAccessors.CreatedAt(((UploadTokenEntity)(entry.Entity))),
                DateTime (IInternalEntry entry) => entry.ReadOriginalValue<DateTime>(createdAt, 2),
                DateTime (IInternalEntry entry) => entry.GetCurrentValue<DateTime>(createdAt));
            createdAt.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            createdAt.TypeMapping = SqliteDateTimeTypeMapping.Default;

            var expiresAt = runtimeEntityType.AddProperty(
                "ExpiresAt",
                typeof(DateTime),
                propertyInfo: typeof(UploadTokenEntity).GetProperty("ExpiresAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UploadTokenEntity).GetField("<ExpiresAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            expiresAt.SetGetter(
                DateTime (UploadTokenEntity instance) => UploadTokenEntityUnsafeAccessors.ExpiresAt(instance),
                bool (UploadTokenEntity instance) => UploadTokenEntityUnsafeAccessors.ExpiresAt(instance) == default(DateTime));
            expiresAt.SetSetter(
                UploadTokenEntity (UploadTokenEntity instance, DateTime value) =>
                {
                    UploadTokenEntityUnsafeAccessors.ExpiresAt(instance) = value;
                    return instance;
                });
            expiresAt.SetMaterializationSetter(
                UploadTokenEntity (UploadTokenEntity instance, DateTime value) =>
                {
                    UploadTokenEntityUnsafeAccessors.ExpiresAt(instance) = value;
                    return instance;
                });
            expiresAt.SetAccessors(
                DateTime (IInternalEntry entry) => UploadTokenEntityUnsafeAccessors.ExpiresAt(((UploadTokenEntity)(entry.Entity))),
                DateTime (IInternalEntry entry) => UploadTokenEntityUnsafeAccessors.ExpiresAt(((UploadTokenEntity)(entry.Entity))),
                DateTime (IInternalEntry entry) => entry.ReadOriginalValue<DateTime>(expiresAt, 3),
                DateTime (IInternalEntry entry) => entry.GetCurrentValue<DateTime>(expiresAt));
            expiresAt.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            expiresAt.TypeMapping = SqliteDateTimeTypeMapping.Default;

            var maxUploads = runtimeEntityType.AddProperty(
                "MaxUploads",
                typeof(int?),
                propertyInfo: typeof(UploadTokenEntity).GetProperty("MaxUploads", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UploadTokenEntity).GetField("<MaxUploads>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            maxUploads.SetGetter(
                int? (UploadTokenEntity instance) => UploadTokenEntityUnsafeAccessors.MaxUploads(instance),
                bool (UploadTokenEntity instance) => !(UploadTokenEntityUnsafeAccessors.MaxUploads(instance).HasValue));
            maxUploads.SetSetter(
                UploadTokenEntity (UploadTokenEntity instance, int? value) =>
                {
                    UploadTokenEntityUnsafeAccessors.MaxUploads(instance) = value;
                    return instance;
                });
            maxUploads.SetMaterializationSetter(
                UploadTokenEntity (UploadTokenEntity instance, int? value) =>
                {
                    UploadTokenEntityUnsafeAccessors.MaxUploads(instance) = value;
                    return instance;
                });
            maxUploads.SetAccessors(
                int? (IInternalEntry entry) => UploadTokenEntityUnsafeAccessors.MaxUploads(((UploadTokenEntity)(entry.Entity))),
                int? (IInternalEntry entry) => UploadTokenEntityUnsafeAccessors.MaxUploads(((UploadTokenEntity)(entry.Entity))),
                int? (IInternalEntry entry) => entry.ReadOriginalValue<int?>(maxUploads, 4),
                int? (IInternalEntry entry) => entry.GetCurrentValue<int?>(maxUploads));
            maxUploads.SetPropertyIndexes(
                index: 4,
                originalValueIndex: 4,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            maxUploads.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));
            maxUploads.SetComparer(new NullableValueComparer<int>(maxUploads.TypeMapping.Comparer));
            maxUploads.SetKeyComparer(new NullableValueComparer<int>(maxUploads.TypeMapping.KeyComparer));

            var uploadsUsed = runtimeEntityType.AddProperty(
                "UploadsUsed",
                typeof(int),
                propertyInfo: typeof(UploadTokenEntity).GetProperty("UploadsUsed", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UploadTokenEntity).GetField("<UploadsUsed>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            uploadsUsed.SetGetter(
                int (UploadTokenEntity instance) => UploadTokenEntityUnsafeAccessors.UploadsUsed(instance),
                bool (UploadTokenEntity instance) => UploadTokenEntityUnsafeAccessors.UploadsUsed(instance) == 0);
            uploadsUsed.SetSetter(
                UploadTokenEntity (UploadTokenEntity instance, int value) =>
                {
                    UploadTokenEntityUnsafeAccessors.UploadsUsed(instance) = value;
                    return instance;
                });
            uploadsUsed.SetMaterializationSetter(
                UploadTokenEntity (UploadTokenEntity instance, int value) =>
                {
                    UploadTokenEntityUnsafeAccessors.UploadsUsed(instance) = value;
                    return instance;
                });
            uploadsUsed.SetAccessors(
                int (IInternalEntry entry) => UploadTokenEntityUnsafeAccessors.UploadsUsed(((UploadTokenEntity)(entry.Entity))),
                int (IInternalEntry entry) => UploadTokenEntityUnsafeAccessors.UploadsUsed(((UploadTokenEntity)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(uploadsUsed, 5),
                int (IInternalEntry entry) => entry.GetCurrentValue<int>(uploadsUsed));
            uploadsUsed.SetPropertyIndexes(
                index: 5,
                originalValueIndex: 5,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            uploadsUsed.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));

            var key = runtimeEntityType.AddKey(
                new[] { token });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { bucketId });

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var token = runtimeEntityType.FindProperty("Token");
            var bucketId = runtimeEntityType.FindProperty("BucketId");
            var createdAt = runtimeEntityType.FindProperty("CreatedAt");
            var expiresAt = runtimeEntityType.FindProperty("ExpiresAt");
            var maxUploads = runtimeEntityType.FindProperty("MaxUploads");
            var uploadsUsed = runtimeEntityType.FindProperty("UploadsUsed");
            var key = runtimeEntityType.FindKey(new[] { token });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNullableFactory<string, int>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<string>(key));
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((UploadTokenEntity)(source.Entity));
                    return ((ISnapshot)(new Snapshot<string, string, DateTime, DateTime, int?, int>((source.GetCurrentValue<string>(token) == null ? null : ((ValueComparer<string>)(((IProperty)token).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(token))), (source.GetCurrentValue<string>(bucketId) == null ? null : ((ValueComparer<string>)(((IProperty)bucketId).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(bucketId))), ((ValueComparer<DateTime>)(((IProperty)createdAt).GetValueComparer())).Snapshot(source.GetCurrentValue<DateTime>(createdAt)), ((ValueComparer<DateTime>)(((IProperty)expiresAt).GetValueComparer())).Snapshot(source.GetCurrentValue<DateTime>(expiresAt)), (source.GetCurrentValue<int?>(maxUploads) == null ? null : ((ValueComparer<int?>)(((IProperty)maxUploads).GetValueComparer())).Snapshot(source.GetCurrentValue<int?>(maxUploads))), ((ValueComparer<int>)(((IProperty)uploadsUsed).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(uploadsUsed)))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => Snapshot.Empty);
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((UploadTokenEntity)(source.Entity));
                    return ((ISnapshot)(new Snapshot<string>((source.GetCurrentValue<string>(token) == null ? null : ((ValueComparer<string>)(((IProperty)token).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<string>(token))))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 6,
                navigationCount: 0,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 6,
                shadowCount: 0,
                relationshipCount: 1,
                storeGeneratedCount: 0));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "UploadTokens");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
